{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vschunkloader",
    "module": "VSChunkLoader-common-1.20.1",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.3.0-beta.12"
          }
        }
      ],
      "files": [
        {
          "name": "VSChunkLoader-common-1.20.1-1.5.0.jar",
          "url": "VSChunkLoader-common-1.20.1-1.5.0.jar",
          "size": 188860,
          "sha512": "8635d42597bda6d8336291eb454eea9a2d3677eb40a48847a77e0c1c0a31147f964e02f16f249c2e8cd7d42af05a7b4355f43c2410024d5becd3997cae68e9ea",
          "sha256": "bd0fa23632343f43a2dab9a4b8bddcf7bb26bc06e55fefa58308730ea6b58dd7",
          "sha1": "5ef6788f4e6c35d136564045efda9f226a58a1a7",
          "md5": "cd22e3cedefe0ef244f3c3f42f19ae1b"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "VSChunkLoader-common-1.20.1",
          "version": "1.5.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader",
          "version": "1.5.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader-common-1.20.1",
          "version": "1.5.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "common",
          "version": "1.5.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api-game",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.3.0-beta.12"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-common-1.20.1",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "VSChunkLoader-common-1.20.1-1.5.0.jar",
          "url": "VSChunkLoader-common-1.20.1-1.5.0.jar",
          "size": 188860,
          "sha512": "8635d42597bda6d8336291eb454eea9a2d3677eb40a48847a77e0c1c0a31147f964e02f16f249c2e8cd7d42af05a7b4355f43c2410024d5becd3997cae68e9ea",
          "sha256": "bd0fa23632343f43a2dab9a4b8bddcf7bb26bc06e55fefa58308730ea6b58dd7",
          "sha1": "5ef6788f4e6c35d136564045efda9f226a58a1a7",
          "md5": "cd22e3cedefe0ef244f3c3f42f19ae1b"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "VSChunkLoader-common-1.20.1",
          "version": "1.5.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader",
          "version": "1.5.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader-common-1.20.1",
          "version": "1.5.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "common",
          "version": "1.5.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VSChunkLoader-common-1.20.1-1.5.0-sources.jar",
          "url": "VSChunkLoader-common-1.20.1-1.5.0-sources.jar",
          "size": 127857,
          "sha512": "879297d0d6f871e42693bf1f14a338203eb8ea50eb98a69becd61823c31064e81af1c6408692c5911f3cf5bbe2bd97e5b76b844d19c7cf35eae26933b44f4369",
          "sha256": "3dc81df3e9e0a6bc0e742841dfeeb2e9f4caf6be88dba01c5b5a3fbf9933a82d",
          "sha1": "055354c67a60cbff44c84f39071ef8c2782fb1f0",
          "md5": "773652e17ccb8dab24d5229d7a1cbf01"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "VSChunkLoader-common-1.20.1",
          "version": "1.5.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader",
          "version": "1.5.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader-common-1.20.1",
          "version": "1.5.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "common",
          "version": "1.5.0"
        }
      ]
    }
  ]
}
