{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-common-1.20.1",
    "version": "0.5.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.3+6faf19387f"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.5.8.jar",
          "url": "vtil-common-1.20.1-0.5.8.jar",
          "size": 171424,
          "sha512": "136379250368254e3a35c1be66445b2d42e872e8a2ea442eedc7a659aec5b32df8d6c6b8f438ad5db2d64cb69ea50d756a5ed91df27d8964411ff61e46a0ee5b",
          "sha256": "f84761cdc6c67232d9085e6739f6940c8119ed8c7505202f0b5b81d7a0d1ae90",
          "sha1": "698d968ca1e71a2a4b6d2f4b205744468534896c",
          "md5": "4894007c63a8c5f22b30731b6a484a36"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.5.8"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.5.8"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.3+6faf19387f"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.5.8.jar",
          "url": "vtil-common-1.20.1-0.5.8.jar",
          "size": 171424,
          "sha512": "136379250368254e3a35c1be66445b2d42e872e8a2ea442eedc7a659aec5b32df8d6c6b8f438ad5db2d64cb69ea50d756a5ed91df27d8964411ff61e46a0ee5b",
          "sha256": "f84761cdc6c67232d9085e6739f6940c8119ed8c7505202f0b5b81d7a0d1ae90",
          "sha1": "698d968ca1e71a2a4b6d2f4b205744468534896c",
          "md5": "4894007c63a8c5f22b30731b6a484a36"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.5.8"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.5.8"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-common-1.20.1-0.5.8-sources.jar",
          "url": "vtil-common-1.20.1-0.5.8-sources.jar",
          "size": 99465,
          "sha512": "2eb93c105e3a325f33b88cbcba0a11324bfa787ebea6a28c121b6bc527c5ebd95d278d3989d0a765826ea3bcf1421aead4b389cc3bbef992696b3489bf4f62ee",
          "sha256": "05238ddd65ab91a4444dc11de3e01898dd29646ec14538ee2cf8bf720064675e",
          "sha1": "50a9285dac88ac4375abef0436cb84603d67edd3",
          "md5": "d5bf55e0f23984dfd11f87e8bff56361"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.5.8"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.5.8"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.8"
        }
      ]
    }
  ]
}
