{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vschunkloader",
    "module": "VSChunkLoader-common-1.20.1",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.5"
          }
        }
      ],
      "files": [
        {
          "name": "VSChunkLoader-common-1.20.1-2.0.1.jar",
          "url": "VSChunkLoader-common-1.20.1-2.0.1.jar",
          "size": 183166,
          "sha512": "8844b12ed92cffddeb8620460083d829ccea3dd1268461995720fe6178d42a48ea86234b4c0fd52fe7e2422120a23a3cf4a23677b0898b3575ab48dc29314967",
          "sha256": "40b589d491b5f6ef26890311363b5b53f86281b8aeb1863b99f48f74fe423099",
          "sha1": "220a7486c77185dc7ed71a92b6a71efada29e944",
          "md5": "9a719e58310343f8b71196dfd319c6ec"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "VSChunkLoader-common-1.20.1",
          "version": "2.0.1"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "common",
          "version": "2.0.1"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader",
          "version": "2.0.1"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader-common-1.20.1",
          "version": "2.0.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+3d898dfd55"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+3d898dfd55"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+3d898dfd55"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+3d898dfd55"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.5"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-common-1.20.1",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "VSChunkLoader-common-1.20.1-2.0.1.jar",
          "url": "VSChunkLoader-common-1.20.1-2.0.1.jar",
          "size": 183166,
          "sha512": "8844b12ed92cffddeb8620460083d829ccea3dd1268461995720fe6178d42a48ea86234b4c0fd52fe7e2422120a23a3cf4a23677b0898b3575ab48dc29314967",
          "sha256": "40b589d491b5f6ef26890311363b5b53f86281b8aeb1863b99f48f74fe423099",
          "sha1": "220a7486c77185dc7ed71a92b6a71efada29e944",
          "md5": "9a719e58310343f8b71196dfd319c6ec"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "VSChunkLoader-common-1.20.1",
          "version": "2.0.1"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "common",
          "version": "2.0.1"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader",
          "version": "2.0.1"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader-common-1.20.1",
          "version": "2.0.1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VSChunkLoader-common-1.20.1-2.0.1-sources.jar",
          "url": "VSChunkLoader-common-1.20.1-2.0.1-sources.jar",
          "size": 125827,
          "sha512": "93eebde2560fc9b0ea1480c22b935fe8879f0cddb836ac68390d50a4c1304efb6e4ae250ebb6f4914bcb406e07098ef724efd4f6bb97d63dc83f6fb3858cb2ce",
          "sha256": "779a31567d5fdc608e6d2845d3bdb69b2edbbc43a1b453f57ec864c90821fde5",
          "sha1": "5404fac8ca14946cc1c8e176fdd29317d6fe2d2e",
          "md5": "e4695f7939cc63e44fb34eca6f41154f"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "VSChunkLoader-common-1.20.1",
          "version": "2.0.1"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "common",
          "version": "2.0.1"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader",
          "version": "2.0.1"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader-common-1.20.1",
          "version": "2.0.1"
        }
      ]
    }
  ]
}
