{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vsplit",
    "module": "VSplit-fabric-1.20.1",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "VSplit-fabric-1.20.1-0.3.0.jar",
          "url": "VSplit-fabric-1.20.1-0.3.0.jar",
          "size": 1171646,
          "sha512": "89bb7095895be9faa39bffde994ad62fcd0ae23351782ea1379bae20416cce51a7427a9a5c1d973d3b41487d040dcf0054c6818590ecd7911ce2809747fcf247",
          "sha256": "739f0f4e3b13c550b23b8777735894b21189c8437e3d7436d9240d1e59a38b00",
          "sha1": "6f1b9629197c17b86a11563bbeee16654dd357ea",
          "md5": "48e9c3e104446970c40bf9d27010fee4"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-fabric-1.20.1",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "fabric",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-fabric-1.20.1",
          "version": "0.3.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.github.litermc.vsplit",
          "module": "VSplit-common-1.20.1",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-fabric-1.20.1",
          "version": {
            "requires": "0.4.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config",
          "version": {
            "requires": "6.4.90"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+fabric"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric",
          "version": {
            "requires": "6.0.8.0+build.1734-mc1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "VSplit-fabric-1.20.1-0.3.0.jar",
          "url": "VSplit-fabric-1.20.1-0.3.0.jar",
          "size": 1171646,
          "sha512": "89bb7095895be9faa39bffde994ad62fcd0ae23351782ea1379bae20416cce51a7427a9a5c1d973d3b41487d040dcf0054c6818590ecd7911ce2809747fcf247",
          "sha256": "739f0f4e3b13c550b23b8777735894b21189c8437e3d7436d9240d1e59a38b00",
          "sha1": "6f1b9629197c17b86a11563bbeee16654dd357ea",
          "md5": "48e9c3e104446970c40bf9d27010fee4"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-fabric-1.20.1",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "fabric",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-fabric-1.20.1",
          "version": "0.3.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VSplit-fabric-1.20.1-0.3.0-sources.jar",
          "url": "VSplit-fabric-1.20.1-0.3.0-sources.jar",
          "size": 148367,
          "sha512": "8af11da5e6a8aed069c12958bdc4a0ef8b494428756c2ca4cc705ff694a05e64e79780521da80f9767f3596bc30dce09391763cdcc6efbcb9e87cdbc1585d72b",
          "sha256": "07968a0e337d2c8b503ce736abc98491973a835b3c9e60afa33a14236fa1e0d5",
          "sha1": "73219cea368fa775ac5b92cb36afd1acb3cab569",
          "md5": "bf50c65f541a1e7c83f6ca2d0fa449e0"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-fabric-1.20.1",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "fabric",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-fabric-1.20.1",
          "version": "0.3.0"
        }
      ]
    }
  ]
}
