{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-fabric-1.20.1",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.6.1.jar",
          "url": "vtil-fabric-1.20.1-0.6.1.jar",
          "size": 603921,
          "sha512": "567e70880f2f143b03ba1731f58fa24cd1a22ead1d991a195c6dc82ea69ca0248c10818c66bb598624648a7dadb4d94b5055d5c45e38063b126bb750ccf584f7",
          "sha256": "a6103175961b225018af642ab270f163053e0f21057a6dc271ad2b360c6b3a00",
          "sha1": "f106cdd6d7b0a67b44163468d56624986206f8bd",
          "md5": "3b91db4cd8528e6201faf353b82746b8"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.6.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.6.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.6.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-common-1.20.1",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config",
          "version": {
            "requires": "6.4.90"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+fabric"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric",
          "version": {
            "requires": "6.0.8.0+build.1734-mc1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.6.1.jar",
          "url": "vtil-fabric-1.20.1-0.6.1.jar",
          "size": 603921,
          "sha512": "567e70880f2f143b03ba1731f58fa24cd1a22ead1d991a195c6dc82ea69ca0248c10818c66bb598624648a7dadb4d94b5055d5c45e38063b126bb750ccf584f7",
          "sha256": "a6103175961b225018af642ab270f163053e0f21057a6dc271ad2b360c6b3a00",
          "sha1": "f106cdd6d7b0a67b44163468d56624986206f8bd",
          "md5": "3b91db4cd8528e6201faf353b82746b8"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.6.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.6.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.6.1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.6.1-sources.jar",
          "url": "vtil-fabric-1.20.1-0.6.1-sources.jar",
          "size": 111613,
          "sha512": "236905ce0b5cb8a768361aca88fb0eebf02d0b0d150cc21702e891821aac2fe6f3ca70f0936b9d676b7b9e9440b59c879355dff2839a9d5fe690e4faeac5989f",
          "sha256": "0531dd2cec9e66245e969013d893ae65ac79c5de23b4c83bd05063df23a2d8c3",
          "sha1": "8bd3de9647b6d30aef3dd81288bcad300881f5ac",
          "md5": "d1b69d1a79391678239bca7ecdadbd9f"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.6.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.6.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.6.1"
        }
      ]
    }
  ]
}
