{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vsplit",
    "module": "VSplit-common-1.20.1",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.3.0-beta.11"
          }
        }
      ],
      "files": [
        {
          "name": "VSplit-common-1.20.1-0.1.0.jar",
          "url": "VSplit-common-1.20.1-0.1.0.jar",
          "size": 66077,
          "sha512": "b6486ed1af112d7b8f885d8c2eb37ab73e2f5d3db6e2c49b3e108a8ba27990249b83b6e329dbd520fc7f0eb84b6d5fd5dd6ac941295d1d26c41e4f69ca0f1590",
          "sha256": "28b111733effcadea40db20b1b6234e5c3ea346de7e5b6ba43571c0d0be2f131",
          "sha1": "a3a585715987af2cd48d04bbad3b96633482c139",
          "md5": "81772a25abfde0550897dd464638d6fe"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-common-1.20.1",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "common",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-common-1.20.1",
          "version": "0.1.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api-game",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.3.0-beta.11"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-common-1.20.1",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "VSplit-common-1.20.1-0.1.0.jar",
          "url": "VSplit-common-1.20.1-0.1.0.jar",
          "size": 66077,
          "sha512": "b6486ed1af112d7b8f885d8c2eb37ab73e2f5d3db6e2c49b3e108a8ba27990249b83b6e329dbd520fc7f0eb84b6d5fd5dd6ac941295d1d26c41e4f69ca0f1590",
          "sha256": "28b111733effcadea40db20b1b6234e5c3ea346de7e5b6ba43571c0d0be2f131",
          "sha1": "a3a585715987af2cd48d04bbad3b96633482c139",
          "md5": "81772a25abfde0550897dd464638d6fe"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-common-1.20.1",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "common",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-common-1.20.1",
          "version": "0.1.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VSplit-common-1.20.1-0.1.0-sources.jar",
          "url": "VSplit-common-1.20.1-0.1.0-sources.jar",
          "size": 40958,
          "sha512": "5ce06daa2ddc25009a9a76512f88cf467470a517151df925a9cca1771a43f755f9e9659f33c797506071863785f85eb2fadbdc12131b016adc822c19e13e5339",
          "sha256": "924ae0900308241fc8b8ec4d50bc99a1367a69f6aa402454ac41143d45ed3bd6",
          "sha1": "5c6ff376a4128956197315dd631d9d29792bdc9c",
          "md5": "db2d10299f0916e3a3f5b40bfd314f60"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-common-1.20.1",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "common",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-common-1.20.1",
          "version": "0.1.0"
        }
      ]
    }
  ]
}
