{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-fabric-1.20.1",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.4.1.jar",
          "url": "vtil-fabric-1.20.1-0.4.1.jar",
          "size": 576284,
          "sha512": "f512d2fd1b916fec7ca2f1e4cb518dfd085f6bd3774268372a443e7d898c7bb44d81ffc52d412df843228ef7a2d21730c1fcb6b4074d0dc4958da7909894d1be",
          "sha256": "a403710010235a6c54fdfc930b9807216d6089f05a5a691792b2e014c463e659",
          "sha1": "9fbb6815feb7fbe59d0235d214b6b5baddd0a84c",
          "md5": "f11225b073b37716982ebcc6e0d3bbae"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.4.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.4.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.4.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-common-1.20.1",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config",
          "version": {
            "requires": "6.4.90"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+fabric"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric",
          "version": {
            "requires": "6.0.8.0+build.1734-mc1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.4.1.jar",
          "url": "vtil-fabric-1.20.1-0.4.1.jar",
          "size": 576284,
          "sha512": "f512d2fd1b916fec7ca2f1e4cb518dfd085f6bd3774268372a443e7d898c7bb44d81ffc52d412df843228ef7a2d21730c1fcb6b4074d0dc4958da7909894d1be",
          "sha256": "a403710010235a6c54fdfc930b9807216d6089f05a5a691792b2e014c463e659",
          "sha1": "9fbb6815feb7fbe59d0235d214b6b5baddd0a84c",
          "md5": "f11225b073b37716982ebcc6e0d3bbae"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.4.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.4.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.4.1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.4.1-sources.jar",
          "url": "vtil-fabric-1.20.1-0.4.1-sources.jar",
          "size": 98041,
          "sha512": "93ab71a4a155dca51a6e3f239b81bdb5610116857a7467c90122d32f8a4812850e1acc4baebf6a8290075464c53347385c9c060db3ead9bc0302e73a6f19409a",
          "sha256": "0bf4ef9a064aae655f0c66592d942a2a7f6373a5e0abb13484ef42ea0f1a8689",
          "sha1": "63b0775e96c64c83852a92351906d99e4c33a52f",
          "md5": "731934c0b517e2a19e85f2c5d6c53561"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.4.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.4.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.4.1"
        }
      ]
    }
  ]
}
