{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-forge-1.20.1",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-forge-1.20.1-0.6.0.jar",
          "url": "vtil-forge-1.20.1-0.6.0.jar",
          "size": 823923,
          "sha512": "2c5298b2d5ff92c831872538c9f6086cfb35f12e54edad93fd073513ca14121b052dce6427bfb3c9575d4356919cffbd817b18634bdcbdb11b749e78e9c45bd9",
          "sha256": "61fd906b5d4583ddf98a87467b8d0605cdff608a77422c3a6897d23c5514d13f",
          "sha1": "e5d2ee9ab5aa91b2c9281adb160f1bf5cffb32fa",
          "md5": "abf3e313c458ed07bb7c04481d822a2a"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.6.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.6.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.6.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+forge"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "6.0.8-289"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        }
      ],
      "files": [
        {
          "name": "vtil-forge-1.20.1-0.6.0.jar",
          "url": "vtil-forge-1.20.1-0.6.0.jar",
          "size": 823923,
          "sha512": "2c5298b2d5ff92c831872538c9f6086cfb35f12e54edad93fd073513ca14121b052dce6427bfb3c9575d4356919cffbd817b18634bdcbdb11b749e78e9c45bd9",
          "sha256": "61fd906b5d4583ddf98a87467b8d0605cdff608a77422c3a6897d23c5514d13f",
          "sha1": "e5d2ee9ab5aa91b2c9281adb160f1bf5cffb32fa",
          "md5": "abf3e313c458ed07bb7c04481d822a2a"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.6.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.6.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.6.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-forge-1.20.1-0.6.0-sources.jar",
          "url": "vtil-forge-1.20.1-0.6.0-sources.jar",
          "size": 112451,
          "sha512": "f8465b9f8a297c21366d9d1e9beda7df06f45ba12fa747f0b0579c68cc49dc8eb50553516ac412ff4c7e693adeeef69dfc84189e104d34ffec5aae12a09f17d3",
          "sha256": "ad1069b933aec744c1cc345c20866f7a5fad849960f4dce3b322cae07c38a2dd",
          "sha1": "6d584fcc75e6bb288e992bfc0c314cc8533f9d2a",
          "md5": "24a4cba311fc427795792b7b6f377dfd"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.6.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.6.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.6.0"
        }
      ]
    }
  ]
}
