{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-forge-1.20.1",
    "version": "0.5.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-forge-1.20.1-0.5.8.jar",
          "url": "vtil-forge-1.20.1-0.5.8.jar",
          "size": 816546,
          "sha512": "4c43b5f52b956f642961c0a248fee34c4de226b6c0dd764d0d9bd4a9b39c3c99e575a31ef5776bebd6da6bf308e8340279d436e94c19892927a46d506b839be8",
          "sha256": "5a3428902450fa34036584d1b33a58017d35ed67d065247500bfa08a38c424d4",
          "sha1": "577e92574d2c50e0a1ec86ab46d7b1c99caed241",
          "md5": "138a4067aa7727ffbeb248548ef4464e"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.5.8"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.5.8"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+forge"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "6.0.8-289"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        }
      ],
      "files": [
        {
          "name": "vtil-forge-1.20.1-0.5.8.jar",
          "url": "vtil-forge-1.20.1-0.5.8.jar",
          "size": 816546,
          "sha512": "4c43b5f52b956f642961c0a248fee34c4de226b6c0dd764d0d9bd4a9b39c3c99e575a31ef5776bebd6da6bf308e8340279d436e94c19892927a46d506b839be8",
          "sha256": "5a3428902450fa34036584d1b33a58017d35ed67d065247500bfa08a38c424d4",
          "sha1": "577e92574d2c50e0a1ec86ab46d7b1c99caed241",
          "md5": "138a4067aa7727ffbeb248548ef4464e"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.5.8"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.5.8"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-forge-1.20.1-0.5.8-sources.jar",
          "url": "vtil-forge-1.20.1-0.5.8-sources.jar",
          "size": 109618,
          "sha512": "0f16cea5bb7a5270b0c2c268080d8a540efca078b456e74c258c908e2fe2db185ce384b6f562be84456ec1d6e4e20491e44cde4b0775f278811abb805257cf90",
          "sha256": "46dbf432ba1933ad4a3676095f080e8f655eec76ec3f1df5b6c534cd1a85078f",
          "sha1": "408d2e35346c14b7b3fabe5586ecaee830dacd04",
          "md5": "a3cf5d9e6e1028ee67f847ea0f8d8b8d"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.5.8"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.5.8"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.8"
        }
      ]
    }
  ]
}
