{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vsplit",
    "module": "VSplit-common-1.20.1",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.3.0-beta.11"
          }
        }
      ],
      "files": [
        {
          "name": "VSplit-common-1.20.1-0.2.0.jar",
          "url": "VSplit-common-1.20.1-0.2.0.jar",
          "size": 168092,
          "sha512": "b26a797b723d2702ce0a9af838931c27519541390d880e74ee5d3eaea3a2ddd2003bd915a35efd6da5aa7bb14fe28a25e2f46248e0810150cd2286d6f94c67d7",
          "sha256": "264953d614696c4737f5ccfc926799eb95827e5f546fbacdf7d9bf80a4337a68",
          "sha1": "b36c81ecaea67e9d386f5f9767aa41baf46d9085",
          "md5": "54e89bc3ff80950a708fa4bb90b31106"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "common",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-common-1.20.1",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-common-1.20.1",
          "version": "0.2.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api-game",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.3.0-beta.11"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-common-1.20.1",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "VSplit-common-1.20.1-0.2.0.jar",
          "url": "VSplit-common-1.20.1-0.2.0.jar",
          "size": 168092,
          "sha512": "b26a797b723d2702ce0a9af838931c27519541390d880e74ee5d3eaea3a2ddd2003bd915a35efd6da5aa7bb14fe28a25e2f46248e0810150cd2286d6f94c67d7",
          "sha256": "264953d614696c4737f5ccfc926799eb95827e5f546fbacdf7d9bf80a4337a68",
          "sha1": "b36c81ecaea67e9d386f5f9767aa41baf46d9085",
          "md5": "54e89bc3ff80950a708fa4bb90b31106"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "common",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-common-1.20.1",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-common-1.20.1",
          "version": "0.2.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VSplit-common-1.20.1-0.2.0-sources.jar",
          "url": "VSplit-common-1.20.1-0.2.0-sources.jar",
          "size": 131035,
          "sha512": "a58737c6d620b83bb0d0b258745bd1ddef1c54a3dac247ca94c0cc9ef49815317002ece1e644c743956086d9b7eddd4a57308b5d551ac5e1f3f8577a819da694",
          "sha256": "7447bbcd7b8dcbe91d84ad0cebdf22cd3017db7026aa1385b831bc276b83d152",
          "sha1": "f51b46b0c431e5c1ed826bd2a3878e28df8f1d47",
          "md5": "1d0c6949c6299a11f5e8827fd759cdae"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "common",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-common-1.20.1",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-common-1.20.1",
          "version": "0.2.0"
        }
      ]
    }
  ]
}
