{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-forge-1.20.1",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-forge-1.20.1-0.6.1.jar",
          "url": "vtil-forge-1.20.1-0.6.1.jar",
          "size": 823926,
          "sha512": "ad31cc13ea22b73efbdfb37839462a69b8b8e33deab405893a6dab75697de70fc4355ed6902ce451793438e5a968c3ae0041b47f8d2b6590dad53fe012894910",
          "sha256": "4a88b8520286655913cc10e78f6221addfd8d5507afdb85ba8366cff23f542b8",
          "sha1": "6573b2e059d948e6edfb821b4defd6a488963839",
          "md5": "578414c4406e4ebccb430593d3d1b34b"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.6.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.6.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.6.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+forge"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "6.0.8-289"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        }
      ],
      "files": [
        {
          "name": "vtil-forge-1.20.1-0.6.1.jar",
          "url": "vtil-forge-1.20.1-0.6.1.jar",
          "size": 823926,
          "sha512": "ad31cc13ea22b73efbdfb37839462a69b8b8e33deab405893a6dab75697de70fc4355ed6902ce451793438e5a968c3ae0041b47f8d2b6590dad53fe012894910",
          "sha256": "4a88b8520286655913cc10e78f6221addfd8d5507afdb85ba8366cff23f542b8",
          "sha1": "6573b2e059d948e6edfb821b4defd6a488963839",
          "md5": "578414c4406e4ebccb430593d3d1b34b"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.6.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.6.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.6.1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-forge-1.20.1-0.6.1-sources.jar",
          "url": "vtil-forge-1.20.1-0.6.1-sources.jar",
          "size": 112467,
          "sha512": "0af1d628339e816dfd0bf22ff9737998b77391d8e53a6d32f567780faed1f38c52e71c84b117e57e954160a41c4942f94da76fed901257417ffea5da48be5e5b",
          "sha256": "a6cb0882cec7a9bac70a625312a3ceed7eb803425c0d0fe0b5aad4cfeb83231f",
          "sha1": "dc81dc276639ba4216e85639d8de5ebe9966afda",
          "md5": "3bcd991c825f1f494de7d7bd9270b72b"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.6.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.6.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.6.1"
        }
      ]
    }
  ]
}
