{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-common-1.20.1",
    "version": "0.5.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.3+6faf19387f"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.5.10.jar",
          "url": "vtil-common-1.20.1-0.5.10.jar",
          "size": 171416,
          "sha512": "f076f03be5261e74db985a7209b724fd3d4e90d8e6efa1ba902cd0210345feb52e6f1d5b7866f4029967038eea8fb5fe858380a140db26cf27ebed7b3b6878a0",
          "sha256": "7ed55bfdfbfd6935044197277ef6ca5fb9d8fe3d6d7a16a8462c1d32d819a4eb",
          "sha1": "2061a7b6ad4876eeec0354670f66f19aed2d3aab",
          "md5": "8381e8a2657f5c3fe79370ef9c729abc"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.5.10"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.5.10"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.10"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.3+6faf19387f"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.5.10.jar",
          "url": "vtil-common-1.20.1-0.5.10.jar",
          "size": 171416,
          "sha512": "f076f03be5261e74db985a7209b724fd3d4e90d8e6efa1ba902cd0210345feb52e6f1d5b7866f4029967038eea8fb5fe858380a140db26cf27ebed7b3b6878a0",
          "sha256": "7ed55bfdfbfd6935044197277ef6ca5fb9d8fe3d6d7a16a8462c1d32d819a4eb",
          "sha1": "2061a7b6ad4876eeec0354670f66f19aed2d3aab",
          "md5": "8381e8a2657f5c3fe79370ef9c729abc"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.5.10"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.5.10"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.10"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-common-1.20.1-0.5.10-sources.jar",
          "url": "vtil-common-1.20.1-0.5.10-sources.jar",
          "size": 99459,
          "sha512": "2bbaa76ee0dc8c013e24753db4d5c2aec2f4c5b742b6a11c70cd45521239f6568671c19f5773817e07a4feda76d87c9486844383de0830445d4ca3ca04c5243f",
          "sha256": "e1b6c09021ed6b28746a810b23fb76f0af29b84976103c185b96bf6a4459f2d0",
          "sha1": "504081b892336760060326529e4863e3e9753b5d",
          "md5": "82d41b60a0b9099cf886e2fe06bc9883"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.5.10"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.5.10"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.10"
        }
      ]
    }
  ]
}
