{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vschunkloader",
    "module": "VSChunkLoader-common-1.20.1",
    "version": "2.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.11+c1e5b68ef8"
          }
        }
      ],
      "files": [
        {
          "name": "VSChunkLoader-common-1.20.1-2.0.3.jar",
          "url": "VSChunkLoader-common-1.20.1-2.0.3.jar",
          "size": 177380,
          "sha512": "ad847073d30347be59c07552b90fa0e076fe68ac22e1b0ef3c892506f24a7595e0ff134c2a4fafc1487fb227e90253322bd944796f3277076eadaa131a143aae",
          "sha256": "77b4501e6b4b5d323dfebf95f5a80ada6d7c32160b9840d9d6c2c6c1df5b90ec",
          "sha1": "a5ea35f72ace841ec8c39072d7f9151fd86b29d1",
          "md5": "d1b3e927862c8813d157eaaddd8f90d2"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "common",
          "version": "2.0.3"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "VSChunkLoader-common-1.20.1",
          "version": "2.0.3"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader",
          "version": "2.0.3"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader-common-1.20.1",
          "version": "2.0.3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.11+c1e5b68ef8"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-common-1.20.1",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "VSChunkLoader-common-1.20.1-2.0.3.jar",
          "url": "VSChunkLoader-common-1.20.1-2.0.3.jar",
          "size": 177380,
          "sha512": "ad847073d30347be59c07552b90fa0e076fe68ac22e1b0ef3c892506f24a7595e0ff134c2a4fafc1487fb227e90253322bd944796f3277076eadaa131a143aae",
          "sha256": "77b4501e6b4b5d323dfebf95f5a80ada6d7c32160b9840d9d6c2c6c1df5b90ec",
          "sha1": "a5ea35f72ace841ec8c39072d7f9151fd86b29d1",
          "md5": "d1b3e927862c8813d157eaaddd8f90d2"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "common",
          "version": "2.0.3"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "VSChunkLoader-common-1.20.1",
          "version": "2.0.3"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader",
          "version": "2.0.3"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader-common-1.20.1",
          "version": "2.0.3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VSChunkLoader-common-1.20.1-2.0.3-sources.jar",
          "url": "VSChunkLoader-common-1.20.1-2.0.3-sources.jar",
          "size": 121619,
          "sha512": "c190c7c7cf18517445656f43ef2c6f7dc488672c0fbc09d03e3ba6b600773a2666120eb4e6651cd29007faca4d5299b7c97814fefea632153811a6197efab537",
          "sha256": "079eba9f6d46dadc82307b0ead5c1683d6a61bf54acdf40c2e2ff5b1d2853ac7",
          "sha1": "162be583e1c248e3135c3e4c3b5cf00771d71ee5",
          "md5": "78ef904f6d06abfc945b4cfecb281610"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "common",
          "version": "2.0.3"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "VSChunkLoader-common-1.20.1",
          "version": "2.0.3"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader",
          "version": "2.0.3"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader-common-1.20.1",
          "version": "2.0.3"
        }
      ]
    }
  ]
}
