{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-forge-1.20.1",
    "version": "0.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-forge-1.20.1-0.6.2.jar",
          "url": "vtil-forge-1.20.1-0.6.2.jar",
          "size": 830008,
          "sha512": "b38826dac69c9991ba34f7d8d0f87bda849b41f92102a96365fa0f3ee716305f8f4329547fb1d76fef18d9938aec75ab7ee596c529140acf14b7edf86edf2337",
          "sha256": "3baa13e77eb4fb764d04de12b2d87e3441f67086c56936e4daa5fb0994ff238d",
          "sha1": "6a1877f7f12824892226a42596cbb00e12c829fb",
          "md5": "62975f77fc8e9d3deaee7976d39d514d"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.6.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.6.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.6.2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+forge"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "6.0.8-289"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        }
      ],
      "files": [
        {
          "name": "vtil-forge-1.20.1-0.6.2.jar",
          "url": "vtil-forge-1.20.1-0.6.2.jar",
          "size": 830008,
          "sha512": "b38826dac69c9991ba34f7d8d0f87bda849b41f92102a96365fa0f3ee716305f8f4329547fb1d76fef18d9938aec75ab7ee596c529140acf14b7edf86edf2337",
          "sha256": "3baa13e77eb4fb764d04de12b2d87e3441f67086c56936e4daa5fb0994ff238d",
          "sha1": "6a1877f7f12824892226a42596cbb00e12c829fb",
          "md5": "62975f77fc8e9d3deaee7976d39d514d"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.6.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.6.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.6.2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-forge-1.20.1-0.6.2-sources.jar",
          "url": "vtil-forge-1.20.1-0.6.2-sources.jar",
          "size": 114030,
          "sha512": "e1d2e99578e82d2396befce775083353b21ce9885f3481ff7fa1bc605a316da415cbb8e99b1e81b8f854cb22813c2eaebe0c626a770610ec5cb3bc53a54b91ad",
          "sha256": "5fac9fe810fb886972de82fc6fc751f07b3930952ccdde76881c20dfb2964824",
          "sha1": "ee307ff2b2803f1098e1e0601a1bb60ff223f8ed",
          "md5": "799f6242b105a52e9c22263b927e6792"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.6.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.6.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.6.2"
        }
      ]
    }
  ]
}
