{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vschunkloader",
    "module": "VSChunkLoader-common-1.20.1",
    "version": "2.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.11+c1e5b68ef8"
          }
        }
      ],
      "files": [
        {
          "name": "VSChunkLoader-common-1.20.1-2.0.2.jar",
          "url": "VSChunkLoader-common-1.20.1-2.0.2.jar",
          "size": 179702,
          "sha512": "c3c2afd0488e7f2debb56df438ddda6665268e864261fc9d48c20a2c4bf12e8e494f5fa94da55b2c8cb53f4f96bef2e1ef1dde2130af4dd2d6c915e34b1fd27d",
          "sha256": "1c42ad9a8517b894ba81529c11316aff7b0e1f4f555648664dd2f64d7fc0951d",
          "sha1": "af9debf40b44af2158ae35e38ff4e1becfa6c9e4",
          "md5": "d7fb8b237a5f31085accd76bb5787951"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "VSChunkLoader-common-1.20.1",
          "version": "2.0.2"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "common",
          "version": "2.0.2"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader",
          "version": "2.0.2"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader-common-1.20.1",
          "version": "2.0.2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.11+c1e5b68ef8"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-common-1.20.1",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "VSChunkLoader-common-1.20.1-2.0.2.jar",
          "url": "VSChunkLoader-common-1.20.1-2.0.2.jar",
          "size": 179702,
          "sha512": "c3c2afd0488e7f2debb56df438ddda6665268e864261fc9d48c20a2c4bf12e8e494f5fa94da55b2c8cb53f4f96bef2e1ef1dde2130af4dd2d6c915e34b1fd27d",
          "sha256": "1c42ad9a8517b894ba81529c11316aff7b0e1f4f555648664dd2f64d7fc0951d",
          "sha1": "af9debf40b44af2158ae35e38ff4e1becfa6c9e4",
          "md5": "d7fb8b237a5f31085accd76bb5787951"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "VSChunkLoader-common-1.20.1",
          "version": "2.0.2"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "common",
          "version": "2.0.2"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader",
          "version": "2.0.2"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader-common-1.20.1",
          "version": "2.0.2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VSChunkLoader-common-1.20.1-2.0.2-sources.jar",
          "url": "VSChunkLoader-common-1.20.1-2.0.2-sources.jar",
          "size": 123519,
          "sha512": "218ac2f00652c0e1dba010e5728b412bd7ab3640655c5323fb43277efe27e16157bc9ebc0be71b0df144a075968817d037513e48f7e8e1fd53ebe6daf900cd6b",
          "sha256": "00ae73645ae952a3da0e600e02f1a5510d79063c588f667f29a6d5ecb0affb7c",
          "sha1": "fc3094132e14f56e7f41114f40e8ede4ffb1c215",
          "md5": "992b8af49775892d25fcd3e675c44a8e"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "VSChunkLoader-common-1.20.1",
          "version": "2.0.2"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "common",
          "version": "2.0.2"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader",
          "version": "2.0.2"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader-common-1.20.1",
          "version": "2.0.2"
        }
      ]
    }
  ]
}
