{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vsplit",
    "module": "VSplit-forge-1.20.1",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-forge",
          "version": {
            "requires": "2.3.0-beta.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "VSplit-forge-1.20.1-0.2.0.jar",
          "url": "VSplit-forge-1.20.1-0.2.0.jar",
          "size": 1586246,
          "sha512": "6ccd125fc18bea5c7ee2c0c27cbe1c186a922af56c14e123fec9d5e9b3f3281ee14ff3d91ba0c3aae1e6025f8b7d231dc1f0a55346ae8c9854bbac2d57cdc360",
          "sha256": "809a2c98555bf950dfbdfbfff5af6ca14f863b8ce320810fb01cc3194a5363d2",
          "sha1": "fb5e4efe097b8c57f0a191615aea91f3de3b588a",
          "md5": "f7798c845817b33a79664bf1f19ecf91"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-forge-1.20.1",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "forge",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-forge-1.20.1",
          "version": "0.2.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api-game",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-forge",
          "version": {
            "requires": "2.3.0-beta.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-forge-1.20.1",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+forge"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "6.0.8-289"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        }
      ],
      "files": [
        {
          "name": "VSplit-forge-1.20.1-0.2.0.jar",
          "url": "VSplit-forge-1.20.1-0.2.0.jar",
          "size": 1586246,
          "sha512": "6ccd125fc18bea5c7ee2c0c27cbe1c186a922af56c14e123fec9d5e9b3f3281ee14ff3d91ba0c3aae1e6025f8b7d231dc1f0a55346ae8c9854bbac2d57cdc360",
          "sha256": "809a2c98555bf950dfbdfbfff5af6ca14f863b8ce320810fb01cc3194a5363d2",
          "sha1": "fb5e4efe097b8c57f0a191615aea91f3de3b588a",
          "md5": "f7798c845817b33a79664bf1f19ecf91"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-forge-1.20.1",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "forge",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-forge-1.20.1",
          "version": "0.2.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VSplit-forge-1.20.1-0.2.0-sources.jar",
          "url": "VSplit-forge-1.20.1-0.2.0-sources.jar",
          "size": 141399,
          "sha512": "02e78484656967cbf6e022bea139d6ec776460d88374fe68dfc9a751e3594651246cbfbbb9c0295affc73de596faa974de97ad2297cf9bada184d6bff1a9aaa0",
          "sha256": "081d74e401e9888a86c40304ffa96902300112a8480fe8f67d7b5f41b4d27362",
          "sha1": "ae0550b6b6ac90ec32e3b7fbeabf81a387e34224",
          "md5": "8bd2f1f4b771e59cd274387318a585ff"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-forge-1.20.1",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "forge",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-forge-1.20.1",
          "version": "0.2.0"
        }
      ]
    }
  ]
}
