{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vsplit",
    "module": "VSplit-forge-1.20.1",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-forge",
          "version": {
            "requires": "2.3.0-beta.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "VSplit-forge-1.20.1-0.2.0.jar",
          "url": "VSplit-forge-1.20.1-0.2.0.jar",
          "size": 1586247,
          "sha512": "13efaa1239302d54fd14a80c449199b7e45302be8f72b9179c395e9116f0cfa11ec0e34504a0f50872db899cbb0b0c676aa591c46606191aa5b14172e804df62",
          "sha256": "9974940e35a1d974fc43c44b7cac5422982d91493e8917d384f37f74bf9f5a88",
          "sha1": "e8de6f096def4b4e35b1d71fba2108f5da53a7b1",
          "md5": "2ccbece79223db18ec2eca62baabcec2"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-forge-1.20.1",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "forge",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-forge-1.20.1",
          "version": "0.2.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api-game",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-forge",
          "version": {
            "requires": "2.3.0-beta.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-forge-1.20.1",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+forge"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "6.0.8-289"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        }
      ],
      "files": [
        {
          "name": "VSplit-forge-1.20.1-0.2.0.jar",
          "url": "VSplit-forge-1.20.1-0.2.0.jar",
          "size": 1586247,
          "sha512": "13efaa1239302d54fd14a80c449199b7e45302be8f72b9179c395e9116f0cfa11ec0e34504a0f50872db899cbb0b0c676aa591c46606191aa5b14172e804df62",
          "sha256": "9974940e35a1d974fc43c44b7cac5422982d91493e8917d384f37f74bf9f5a88",
          "sha1": "e8de6f096def4b4e35b1d71fba2108f5da53a7b1",
          "md5": "2ccbece79223db18ec2eca62baabcec2"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-forge-1.20.1",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "forge",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-forge-1.20.1",
          "version": "0.2.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VSplit-forge-1.20.1-0.2.0-sources.jar",
          "url": "VSplit-forge-1.20.1-0.2.0-sources.jar",
          "size": 141401,
          "sha512": "d934e01a0b56bcb6ad85d602a548eba2cbbb12665ebcf5542990d29ae344d61b5ab4d459057ec482c4a75d22f812511341935d6928250997c1a5c125411523fa",
          "sha256": "08b74829a2a606b3fbefd8e6f0e91cabaf9c40a0e650c74bded7c19b953e546c",
          "sha1": "a6e1091aaecf77443ab4294caa91370c26b5a551",
          "md5": "0df148a188126f77a943e0b5e9050a9f"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-forge-1.20.1",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "forge",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-forge-1.20.1",
          "version": "0.2.0"
        }
      ]
    }
  ]
}
