{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-common-1.20.1",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.11+9a09dd2609"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.6.1.jar",
          "url": "vtil-common-1.20.1-0.6.1.jar",
          "size": 178727,
          "sha512": "789b7df47cd9a9eb8cc24cc678781ec0bad94cb837ec93f9245f339f99402ce9b8bcb1a268d387f7d7f04694cde8f8d6685f5847008eea0efe816faeeace233e",
          "sha256": "acfd0fc905749f7cc179adb3eb2439a72ebf359f664af1b243057c2cee6f6ba5",
          "sha1": "ade9e76dae9e3adfa5f01d8b13c10c34a312be46",
          "md5": "7e6fabac5efbee69362e155d00106028"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.6.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.6.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.6.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.11+9a09dd2609"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.6.1.jar",
          "url": "vtil-common-1.20.1-0.6.1.jar",
          "size": 178727,
          "sha512": "789b7df47cd9a9eb8cc24cc678781ec0bad94cb837ec93f9245f339f99402ce9b8bcb1a268d387f7d7f04694cde8f8d6685f5847008eea0efe816faeeace233e",
          "sha256": "acfd0fc905749f7cc179adb3eb2439a72ebf359f664af1b243057c2cee6f6ba5",
          "sha1": "ade9e76dae9e3adfa5f01d8b13c10c34a312be46",
          "md5": "7e6fabac5efbee69362e155d00106028"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.6.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.6.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.6.1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-common-1.20.1-0.6.1-sources.jar",
          "url": "vtil-common-1.20.1-0.6.1-sources.jar",
          "size": 102264,
          "sha512": "f16cf9d348ebf9e02e826874e5f21014831e67b0214a3b657fbeb39b46e7b7eb93043950c9bc1a6af01d5c1c538e7cd8555517afcef56aab48d056a37e44cada",
          "sha256": "19b914a19bb5e13e6cb6782c6cf1a57b7bd3965d424552c176308f86a8a87931",
          "sha1": "9a1982f0cafa360b7c9af511f41f5c38ef6f418d",
          "md5": "43b684eebd759b8fcf09ac746713eb21"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.6.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.6.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.6.1"
        }
      ]
    }
  ]
}
