{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-common-1.20.1",
    "version": "0.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.3.0-beta.11"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.3.2.jar",
          "url": "vtil-common-1.20.1-0.3.2.jar",
          "size": 131527,
          "sha512": "ddd43e9a2aca3187f53402c9631cbbddbf576840e2fc9b3bf5b1ce577672445e85002eef1d4f4f4c282ddb271af332a75add6df6b6d954ea2885b8e2d4ddaf9d",
          "sha256": "dbbb02213441282dcd19876aa0431dc0ec90d398c3a555647edc605f0d8928d2",
          "sha1": "649dde9f689a1b17e9cd930c95fc8d6e0cf88594",
          "md5": "1e589f27b0cbbf696e1f224459c58dd3"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.3.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.3.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.3.2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api-game",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.3.0-beta.11"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.3.2.jar",
          "url": "vtil-common-1.20.1-0.3.2.jar",
          "size": 131527,
          "sha512": "ddd43e9a2aca3187f53402c9631cbbddbf576840e2fc9b3bf5b1ce577672445e85002eef1d4f4f4c282ddb271af332a75add6df6b6d954ea2885b8e2d4ddaf9d",
          "sha256": "dbbb02213441282dcd19876aa0431dc0ec90d398c3a555647edc605f0d8928d2",
          "sha1": "649dde9f689a1b17e9cd930c95fc8d6e0cf88594",
          "md5": "1e589f27b0cbbf696e1f224459c58dd3"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.3.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.3.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.3.2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-common-1.20.1-0.3.2-sources.jar",
          "url": "vtil-common-1.20.1-0.3.2-sources.jar",
          "size": 81448,
          "sha512": "48fa6a3a45f3c75861714dfcd09579caaab998bdaa83bc6150804a43d658a376e34df6e971b858e85437300e8d23ac18e68b065ef62c32e4b6c0bfb7fc03ca5f",
          "sha256": "9aedafd40523f62d83b84887cb52bbcd44c07d272dfed15ee5987ed7bfdc7322",
          "sha1": "c795e8c714cc48cef15e884e5805fa394ec38b0b",
          "md5": "c2930038d4da5ca6b25f242715112ad1"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.3.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.3.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.3.2"
        }
      ]
    }
  ]
}
