{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-common-1.20.1",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.3+6faf19387f"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.6.0.jar",
          "url": "vtil-common-1.20.1-0.6.0.jar",
          "size": 178725,
          "sha512": "173f85c0b058c3a4afa7c487a116a5ebb9ff54765dc7d3b148ed41580437065d1307196f79820fc9635bb6473d57ed747ef9ce088902b94f46618e16a285f492",
          "sha256": "cb58ce1e3f34f8f7bab6da01313315f63db366b5cb95dc9eae6d30b694a52424",
          "sha1": "5bb0b3d59fbd276e79f119e34d19d74059b061f0",
          "md5": "85002e39985ac139259e269e99b89935"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.6.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.6.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.6.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.3+6faf19387f"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.6.0.jar",
          "url": "vtil-common-1.20.1-0.6.0.jar",
          "size": 178725,
          "sha512": "173f85c0b058c3a4afa7c487a116a5ebb9ff54765dc7d3b148ed41580437065d1307196f79820fc9635bb6473d57ed747ef9ce088902b94f46618e16a285f492",
          "sha256": "cb58ce1e3f34f8f7bab6da01313315f63db366b5cb95dc9eae6d30b694a52424",
          "sha1": "5bb0b3d59fbd276e79f119e34d19d74059b061f0",
          "md5": "85002e39985ac139259e269e99b89935"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.6.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.6.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.6.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-common-1.20.1-0.6.0-sources.jar",
          "url": "vtil-common-1.20.1-0.6.0-sources.jar",
          "size": 102257,
          "sha512": "c1a0c3af0b53980b86c6a78e59f9ff10b6ab232b15be1068ffaa1ffd18ff678ff7099357914ee4cb92bead29d8949d6d66bde6a8dfb7d7dc9042fac4a224d5b6",
          "sha256": "f964d90e6fdb54c69349943b6746cd869a755c0eee232528c4f7198d49cd174e",
          "sha1": "0fee856aab811c0e5eab6adc8e456eeadd42bfa6",
          "md5": "ae17970ed254142c2b14ef3d36dcaea1"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.6.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.6.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.6.0"
        }
      ]
    }
  ]
}
