{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-common-1.20.1",
    "version": "0.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.0+99a5c6e40f"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.5.3.jar",
          "url": "vtil-common-1.20.1-0.5.3.jar",
          "size": 166469,
          "sha512": "ba63edb5fe59b236264fea042359d2f9520a1e53bf9754d2f77ff808a1233f249ed34e0c6b775e9127d31b7e50668d94b0ebb6d4aa4ecb42b5096dc0ebc05a15",
          "sha256": "583c96622c45afd89571af8c9eeba9c21c6fe1cc03d8c1414b4b736c676b009c",
          "sha1": "136160103d7adfb7174b7c1cbca4e973c42c7bfb",
          "md5": "78055383ee519001f54acf9697e7e40c"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.3"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.5.3"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.5.3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+b8f10be9b1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+b8f10be9b1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+b8f10be9b1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+b8f10be9b1"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.0+99a5c6e40f"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.5.3.jar",
          "url": "vtil-common-1.20.1-0.5.3.jar",
          "size": 166469,
          "sha512": "ba63edb5fe59b236264fea042359d2f9520a1e53bf9754d2f77ff808a1233f249ed34e0c6b775e9127d31b7e50668d94b0ebb6d4aa4ecb42b5096dc0ebc05a15",
          "sha256": "583c96622c45afd89571af8c9eeba9c21c6fe1cc03d8c1414b4b736c676b009c",
          "sha1": "136160103d7adfb7174b7c1cbca4e973c42c7bfb",
          "md5": "78055383ee519001f54acf9697e7e40c"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.3"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.5.3"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.5.3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-common-1.20.1-0.5.3-sources.jar",
          "url": "vtil-common-1.20.1-0.5.3-sources.jar",
          "size": 97413,
          "sha512": "dc4faed05e0726d0b255d2c568b946583cb34ccf52082d4754ce3997a28e80bb96395b8120a209db16bef6524d0436d3fe1254a5b3ce5b03e94b6409e7ada513",
          "sha256": "2e515ee92cd9985f121f45d3714184f8993d2fcfe79910535e2bf5b81c71b8fd",
          "sha1": "1e28b4aef30c8744a2b07b66fdd8a6a7469f2082",
          "md5": "111e6ba03d126456e6969f95d1b74f18"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.3"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.5.3"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.5.3"
        }
      ]
    }
  ]
}
