{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-forge-1.20.1",
    "version": "0.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-forge",
          "version": {
            "requires": "2.3.0-beta.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vtil-forge-1.20.1-0.3.2.jar",
          "url": "vtil-forge-1.20.1-0.3.2.jar",
          "size": 776461,
          "sha512": "76816d3fd15d45d8e42bf762e951a7ce46033209fee2bab19276e14ce5291c00213e71461d6f4d17d19404773d1937805a33f2f0ea9e0cd38e15513dbaf7174d",
          "sha256": "a93ad73a649b5b3b6a50829f7e7f4aafcad9cbef1c8f8d3b0aed9e4e2973b13f",
          "sha1": "b3c0a229792d87ea235e9a14268d76626a8e75ae",
          "md5": "f68304ca8eec7464205783096696d6a5"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.3.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.3.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.3.2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api-game",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-forge",
          "version": {
            "requires": "2.3.0-beta.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+forge"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "6.0.8-289"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        }
      ],
      "files": [
        {
          "name": "vtil-forge-1.20.1-0.3.2.jar",
          "url": "vtil-forge-1.20.1-0.3.2.jar",
          "size": 776461,
          "sha512": "76816d3fd15d45d8e42bf762e951a7ce46033209fee2bab19276e14ce5291c00213e71461d6f4d17d19404773d1937805a33f2f0ea9e0cd38e15513dbaf7174d",
          "sha256": "a93ad73a649b5b3b6a50829f7e7f4aafcad9cbef1c8f8d3b0aed9e4e2973b13f",
          "sha1": "b3c0a229792d87ea235e9a14268d76626a8e75ae",
          "md5": "f68304ca8eec7464205783096696d6a5"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.3.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.3.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.3.2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-forge-1.20.1-0.3.2-sources.jar",
          "url": "vtil-forge-1.20.1-0.3.2-sources.jar",
          "size": 91525,
          "sha512": "ef508e02f66b27c782137146d6bbc78018b31e9b99763fa6e978e4b729f5f7a70fcdc794be91786731ef5183783ef02701d9558ae0301b68ce3b41c0236c98b1",
          "sha256": "fd684b07a24f470712c93807e3cfe4872c9303c8fef27127b172f670a13e431c",
          "sha1": "d609488cc380e210710c192bb4dfae7ea55d6026",
          "md5": "b513d3630ae18e44c5a4cd83a26fe6f8"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.3.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.3.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.3.2"
        }
      ]
    }
  ]
}
