{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vsplit",
    "module": "VSplit-fabric-1.20.1",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "VSplit-fabric-1.20.1-0.1.4.jar",
          "url": "VSplit-fabric-1.20.1-0.1.4.jar",
          "size": 571750,
          "sha512": "25e181e14760fcd0329458b0177a4f697242fad371ac3ccf3b21dd440a2fa3cb06f5ff2c6336a128a9d3796987f6a2c236353775eb385327ebc119e89baf814c",
          "sha256": "5eb38b4d9cb35465209c7dfe4d9c70863e451dd508f5e33840e049229ae9ce88",
          "sha1": "830e370745641922fbdf1b68af2b49620b142da7",
          "md5": "c438ce9247235aeaf474a17632f4c85a"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.1.4"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-fabric-1.20.1",
          "version": "0.1.4"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-fabric-1.20.1",
          "version": "0.1.4"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "fabric",
          "version": "0.1.4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.github.litermc.vsplit",
          "module": "VSplit-common-1.20.1",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-forge-1.20.1",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config",
          "version": {
            "requires": "6.4.90"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+fabric"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric",
          "version": {
            "requires": "6.0.8.0+build.1734-mc1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "VSplit-fabric-1.20.1-0.1.4.jar",
          "url": "VSplit-fabric-1.20.1-0.1.4.jar",
          "size": 571750,
          "sha512": "25e181e14760fcd0329458b0177a4f697242fad371ac3ccf3b21dd440a2fa3cb06f5ff2c6336a128a9d3796987f6a2c236353775eb385327ebc119e89baf814c",
          "sha256": "5eb38b4d9cb35465209c7dfe4d9c70863e451dd508f5e33840e049229ae9ce88",
          "sha1": "830e370745641922fbdf1b68af2b49620b142da7",
          "md5": "c438ce9247235aeaf474a17632f4c85a"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.1.4"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-fabric-1.20.1",
          "version": "0.1.4"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-fabric-1.20.1",
          "version": "0.1.4"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "fabric",
          "version": "0.1.4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VSplit-fabric-1.20.1-0.1.4-sources.jar",
          "url": "VSplit-fabric-1.20.1-0.1.4-sources.jar",
          "size": 129572,
          "sha512": "28f314fd059d86a20a3892c2f6da7a2c90d1a5caf6d483d7f87dd7d5949fec5760515185ccfd2b59a2ef4233181f3dd07037e56375b5be5d9b5547fb5319754a",
          "sha256": "7c27b7dca178d9c530d918a60bb476eedad495515ec037efe579e2ccf3352fc6",
          "sha1": "fd659932b16a0eb8aeeed3d6327563aed85ba87a",
          "md5": "e07ba4116a176e9f666486ed89b02848"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.1.4"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-fabric-1.20.1",
          "version": "0.1.4"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-fabric-1.20.1",
          "version": "0.1.4"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "fabric",
          "version": "0.1.4"
        }
      ]
    }
  ]
}
