{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-fabric-1.20.1",
    "version": "0.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.3.2.jar",
          "url": "vtil-fabric-1.20.1-0.3.2.jar",
          "size": 556719,
          "sha512": "7ab51b89f5522f5d4de0fd409c268ed224936a209904458b74c4f91631fb995d7f69d494e2e1a619b719f05a6f941481674b3024392f1d6f1511422499750146",
          "sha256": "bf22ab850a1916e44b9e1bce00abd0ff608473d640af7a2c65ba76fa81dca04c",
          "sha1": "7549f238030d4408de63ecb2297620032102f32e",
          "md5": "eaf0a6888f8e2d239ea8b97190d6eb67"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.3.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.3.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.3.2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-common-1.20.1",
          "version": {
            "requires": "0.3.2"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config",
          "version": {
            "requires": "6.4.90"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+fabric"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric",
          "version": {
            "requires": "6.0.8.0+build.1734-mc1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.3.2.jar",
          "url": "vtil-fabric-1.20.1-0.3.2.jar",
          "size": 556719,
          "sha512": "7ab51b89f5522f5d4de0fd409c268ed224936a209904458b74c4f91631fb995d7f69d494e2e1a619b719f05a6f941481674b3024392f1d6f1511422499750146",
          "sha256": "bf22ab850a1916e44b9e1bce00abd0ff608473d640af7a2c65ba76fa81dca04c",
          "sha1": "7549f238030d4408de63ecb2297620032102f32e",
          "md5": "eaf0a6888f8e2d239ea8b97190d6eb67"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.3.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.3.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.3.2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.3.2-sources.jar",
          "url": "vtil-fabric-1.20.1-0.3.2-sources.jar",
          "size": 90793,
          "sha512": "cefcba91944f2199d9cd55a1fbd4000917ee595ab11c3b1cc9c83c7c0ba9965397097e1fa69695c3d1e6cb933fb2e5a2bf2a0521a1909708ba11c9b56b0d03c5",
          "sha256": "72e313ab23d1d2d1ef8b00e12d93da97a33fd84f8d86fce6d2f64eb714d6d5e1",
          "sha1": "286a42229cd14b8ed6acece598fb8763ce6fa5b6",
          "md5": "4b3748074c2a86a08e8bf1eb30a85e8c"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.3.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.3.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.3.2"
        }
      ]
    }
  ]
}
