{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-fabric-1.20.1",
    "version": "0.5.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.5.5.jar",
          "url": "vtil-fabric-1.20.1-0.5.5.jar",
          "size": 592501,
          "sha512": "c6bc1ca08c2725a6c0a45aa26ab8b3846c8b67836eedc3266b33d4535809d9b941ebe3c4ddf65a48977b5dde62eef9dccf828df14ba7e74e19debe6039539f0c",
          "sha256": "abf3b84ae26e98dc17ad31707f81e79936d1862959f3f68366504c26662532c1",
          "sha1": "5a2aa19ddb38b77c52627bf76d8534b2697c5e9d",
          "md5": "8038ee96407be94fede4018d099f228e"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.5.5"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.5"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.5.5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+b8f10be9b1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+b8f10be9b1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+b8f10be9b1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+b8f10be9b1"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-common-1.20.1",
          "version": {
            "requires": "0.5.5"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config",
          "version": {
            "requires": "6.4.90"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+fabric"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric",
          "version": {
            "requires": "6.0.8.0+build.1734-mc1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.5.5.jar",
          "url": "vtil-fabric-1.20.1-0.5.5.jar",
          "size": 592501,
          "sha512": "c6bc1ca08c2725a6c0a45aa26ab8b3846c8b67836eedc3266b33d4535809d9b941ebe3c4ddf65a48977b5dde62eef9dccf828df14ba7e74e19debe6039539f0c",
          "sha256": "abf3b84ae26e98dc17ad31707f81e79936d1862959f3f68366504c26662532c1",
          "sha1": "5a2aa19ddb38b77c52627bf76d8534b2697c5e9d",
          "md5": "8038ee96407be94fede4018d099f228e"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.5.5"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.5"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.5.5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.5.5-sources.jar",
          "url": "vtil-fabric-1.20.1-0.5.5-sources.jar",
          "size": 107377,
          "sha512": "dec261160688ced7453cbb4a502e820d26bbd9198a6eee0804c4f2f97587b5c2d31bf66145d3704e4e3bdc147c8adb47f85e1ea965c71770dcb8c69232bcf535",
          "sha256": "0d14a6126b9bff672361b42254325d7f580e346e2058d8743d20b6037bdc313a",
          "sha1": "10e8bbd037be2d95a1c77a9263bfd3b05aa27f55",
          "md5": "e517953e49af03d59fe146a8b4716c6f"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.5.5"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.5"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.5.5"
        }
      ]
    }
  ]
}
