{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-fabric-1.20.1",
    "version": "0.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.5.6.jar",
          "url": "vtil-fabric-1.20.1-0.5.6.jar",
          "size": 596292,
          "sha512": "e927f95898f27f46a898b00f479de522740ec834b3f771700b7f8398f285f44c8136a7383662f4aa17d64a5b96af1a29d2d399676dfb9f8d012182bab8b5ec50",
          "sha256": "7517d8a942c6f7277a23eb85919635658468b7484595c4c871c014b5310f6a51",
          "sha1": "90d8022546875d20fe3e4a1f693319fb6a432246",
          "md5": "b2d5f278ac096274ffce3b525ec86140"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.5.6"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.6"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.5.6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-common-1.20.1",
          "version": {
            "requires": "0.5.6"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config",
          "version": {
            "requires": "6.4.90"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+fabric"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric",
          "version": {
            "requires": "6.0.8.0+build.1734-mc1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.5.6.jar",
          "url": "vtil-fabric-1.20.1-0.5.6.jar",
          "size": 596292,
          "sha512": "e927f95898f27f46a898b00f479de522740ec834b3f771700b7f8398f285f44c8136a7383662f4aa17d64a5b96af1a29d2d399676dfb9f8d012182bab8b5ec50",
          "sha256": "7517d8a942c6f7277a23eb85919635658468b7484595c4c871c014b5310f6a51",
          "sha1": "90d8022546875d20fe3e4a1f693319fb6a432246",
          "md5": "b2d5f278ac096274ffce3b525ec86140"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.5.6"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.6"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.5.6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.5.6-sources.jar",
          "url": "vtil-fabric-1.20.1-0.5.6-sources.jar",
          "size": 108597,
          "sha512": "820b7918c61d550dc7c5969654d83139f9dd6f9976cc42c14ab54c23be99f6773c7ddcf266112b652e3a626e49b7322eafb40e95b7a592bd451f5f72b561bc51",
          "sha256": "11ada56d13410120d40883b358ac3f016302765cc53eb146354d3eeddeeddb32",
          "sha1": "7ce21ca279579ae0e5578531dfc60ddb5f2c9b30",
          "md5": "c37e18de876b1f37d5a939840f6c9f1a"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.5.6"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.6"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.5.6"
        }
      ]
    }
  ]
}
