{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vschunkloader",
    "module": "VSChunkLoader-common-1.20.1",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.5"
          }
        }
      ],
      "files": [
        {
          "name": "VSChunkLoader-common-1.20.1-2.0.0.jar",
          "url": "VSChunkLoader-common-1.20.1-2.0.0.jar",
          "size": 181820,
          "sha512": "abe4933ae7cd81533fdc982a1c68b15595259d4bfd84999737208bb95b7810c47aa6e48e45415260608d0f7872636ed7ec9d9e43f006b30885865b2d35357332",
          "sha256": "464d1f022e45eb835e9692afe4979f79b48ee929ef718748e7fea2920bbee201",
          "sha1": "6776289bf34ef7ed9c3d3a5e6a5c82c796f1a4ab",
          "md5": "9f454736d9b26af42455c308e41910a1"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "common",
          "version": "2.0.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "VSChunkLoader-common-1.20.1",
          "version": "2.0.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader",
          "version": "2.0.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader-common-1.20.1",
          "version": "2.0.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+3d898dfd55"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+3d898dfd55"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+3d898dfd55"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+3d898dfd55"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.5"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-common-1.20.1",
          "version": {
            "requires": "0.5.5"
          }
        }
      ],
      "files": [
        {
          "name": "VSChunkLoader-common-1.20.1-2.0.0.jar",
          "url": "VSChunkLoader-common-1.20.1-2.0.0.jar",
          "size": 181820,
          "sha512": "abe4933ae7cd81533fdc982a1c68b15595259d4bfd84999737208bb95b7810c47aa6e48e45415260608d0f7872636ed7ec9d9e43f006b30885865b2d35357332",
          "sha256": "464d1f022e45eb835e9692afe4979f79b48ee929ef718748e7fea2920bbee201",
          "sha1": "6776289bf34ef7ed9c3d3a5e6a5c82c796f1a4ab",
          "md5": "9f454736d9b26af42455c308e41910a1"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "common",
          "version": "2.0.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "VSChunkLoader-common-1.20.1",
          "version": "2.0.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader",
          "version": "2.0.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader-common-1.20.1",
          "version": "2.0.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VSChunkLoader-common-1.20.1-2.0.0-sources.jar",
          "url": "VSChunkLoader-common-1.20.1-2.0.0-sources.jar",
          "size": 125143,
          "sha512": "ec43f70216aaad3ef360c20bc3cc5bfed26a11fc55be7ae767bbc9f7bb1a817587ce655e9ba40684e6ebf37c84dd85e8ffa5be82d8074ecc50ba40a670686cdc",
          "sha256": "d681905bdff26688ee2f2a814abd4f4bbd530bc6cdcc102ae9b1e2ceacc99c51",
          "sha1": "7b67b6802c4b9b995d9b1440c29acd28036cf3b2",
          "md5": "420410e446b09323d02521982876878e"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "common",
          "version": "2.0.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "VSChunkLoader-common-1.20.1",
          "version": "2.0.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader",
          "version": "2.0.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader-common-1.20.1",
          "version": "2.0.0"
        }
      ]
    }
  ]
}
