{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-common-1.20.1",
    "version": "0.5.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.0+99a5c6e40f"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.5.5.jar",
          "url": "vtil-common-1.20.1-0.5.5.jar",
          "size": 167309,
          "sha512": "1d50fe027a1b8d3beaf564983e0019f34fc0cd432c9e0b0d4c24a25238761e535b8db12bb52a197a3014b173320284d6c9773142bb80214bb0a047f29a470c89",
          "sha256": "2982c429ae8b81f52adfc87949745e10fc22ae507f005cbfe410d6c556e8102d",
          "sha1": "96de4a8376813993a4632e0565cdd720e49608b0",
          "md5": "801ad64baa0411ad678846aaaccd27d9"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.5"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.5.5"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.5.5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+b8f10be9b1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+b8f10be9b1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+b8f10be9b1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+b8f10be9b1"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.0+99a5c6e40f"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.5.5.jar",
          "url": "vtil-common-1.20.1-0.5.5.jar",
          "size": 167309,
          "sha512": "1d50fe027a1b8d3beaf564983e0019f34fc0cd432c9e0b0d4c24a25238761e535b8db12bb52a197a3014b173320284d6c9773142bb80214bb0a047f29a470c89",
          "sha256": "2982c429ae8b81f52adfc87949745e10fc22ae507f005cbfe410d6c556e8102d",
          "sha1": "96de4a8376813993a4632e0565cdd720e49608b0",
          "md5": "801ad64baa0411ad678846aaaccd27d9"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.5"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.5.5"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.5.5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-common-1.20.1-0.5.5-sources.jar",
          "url": "vtil-common-1.20.1-0.5.5-sources.jar",
          "size": 98032,
          "sha512": "cd0bfc630a276522ea0c710fa9599f8429022389f66c31c912664f5805a2da72d881652b22f474258339376dddf2cb1ce3a8d03a51bd03d04fcb65f364decdd8",
          "sha256": "f72ee566bff4b58cff64d0bf0a28f2948b0f18dc224de5b65887a1b1955b2acf",
          "sha1": "b50ce596078f0f76ddc481cd778fbca9ec021a42",
          "md5": "c137c26696a79af0286ce033d4c79cfc"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.5"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.5.5"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.5.5"
        }
      ]
    }
  ]
}
