{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-fabric-1.20.1",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.3.0.jar",
          "url": "vtil-fabric-1.20.1-0.3.0.jar",
          "size": 555315,
          "sha512": "0535e536cde414c27427edf1807209b07d831a41ca968798151d8e890a397c888dd7573300e7ba5b8356aa0ca969cef3b0cc27a22c1eedc9c050619d3cf8a443",
          "sha256": "b1068f1bc886f7881d2f9b2454d06ab30123900be4f1a999de4767946271a531",
          "sha1": "c5ae20cc752b2296c99c4741464acb09eb6095ec",
          "md5": "afdb7507afefbfffdcccfd864d797dd7"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.3.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-common-1.20.1",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config",
          "version": {
            "requires": "6.4.90"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+fabric"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric",
          "version": {
            "requires": "6.0.8.0+build.1734-mc1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.3.0.jar",
          "url": "vtil-fabric-1.20.1-0.3.0.jar",
          "size": 555315,
          "sha512": "0535e536cde414c27427edf1807209b07d831a41ca968798151d8e890a397c888dd7573300e7ba5b8356aa0ca969cef3b0cc27a22c1eedc9c050619d3cf8a443",
          "sha256": "b1068f1bc886f7881d2f9b2454d06ab30123900be4f1a999de4767946271a531",
          "sha1": "c5ae20cc752b2296c99c4741464acb09eb6095ec",
          "md5": "afdb7507afefbfffdcccfd864d797dd7"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.3.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.3.0-sources.jar",
          "url": "vtil-fabric-1.20.1-0.3.0-sources.jar",
          "size": 90114,
          "sha512": "a034cc3668c5a88b9da458ad9a3dc3296f1cca33f9238035409ded119d3b642e5e8550976f20121d761054b19aa7ff034251803e3ab21de351392c088b5edb63",
          "sha256": "63e14700b29cf88799bbf53bd77f0551e2340062ac588eb709d1aa94f01a043c",
          "sha1": "11db37aed7010e126dc8d34aae24c25aeb7034a8",
          "md5": "5a33d093397b7bff8b2cce9b95195aaa"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.3.0"
        }
      ]
    }
  ]
}
