{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "Vtil-forge-1.20.1",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-forge",
          "version": {
            "requires": "2.3.0-beta.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "Vtil-forge-1.20.1-0.1.0.jar",
          "url": "Vtil-forge-1.20.1-0.1.0.jar",
          "size": 1255223,
          "sha512": "ecfa9eaaa1281983160b1bea133f9ec4e9c5ad58ef7238a903d9e84230ae159df64fcdfc38b01b97b978775bced101109aae9fa414ddbc1ba8d78ff9616f39f6",
          "sha256": "d2e188bccc81f5bd9435e4816ad3ad61dba681536712b19608ce655cda051da8",
          "sha1": "2975a26432db12fb49032196a552e10c726fa51c",
          "md5": "a3417ae3287b6ee09153b3fe3ab048d1"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "Vtil-forge-1.20.1",
          "version": "0.1.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api-game",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-forge",
          "version": {
            "requires": "2.3.0-beta.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+forge"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "6.0.8-289"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        }
      ],
      "files": [
        {
          "name": "Vtil-forge-1.20.1-0.1.0.jar",
          "url": "Vtil-forge-1.20.1-0.1.0.jar",
          "size": 1255223,
          "sha512": "ecfa9eaaa1281983160b1bea133f9ec4e9c5ad58ef7238a903d9e84230ae159df64fcdfc38b01b97b978775bced101109aae9fa414ddbc1ba8d78ff9616f39f6",
          "sha256": "d2e188bccc81f5bd9435e4816ad3ad61dba681536712b19608ce655cda051da8",
          "sha1": "2975a26432db12fb49032196a552e10c726fa51c",
          "md5": "a3417ae3287b6ee09153b3fe3ab048d1"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "Vtil-forge-1.20.1",
          "version": "0.1.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Vtil-forge-1.20.1-0.1.0-sources.jar",
          "url": "Vtil-forge-1.20.1-0.1.0-sources.jar",
          "size": 79713,
          "sha512": "c412be727887dfc80e19eaf2db308b1dfe9ab77a3fe6426a49fe57924658cfdd522d4a598602d06655585686d0ea2a3e955e727201be007212cfe88add61c1fe",
          "sha256": "59b253431dbbf39aab28dc56b5c4bf7d016e7a792cc767bf0222e38a33915521",
          "sha1": "63594885ea81e176dbd6aac4ac881580c3a288c1",
          "md5": "064891bca26e3b5c5928de59c9564942"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "Vtil-forge-1.20.1",
          "version": "0.1.0"
        }
      ]
    }
  ]
}
