{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-forge-1.20.1",
    "version": "0.5.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-forge-1.20.1-0.5.5.jar",
          "url": "vtil-forge-1.20.1-0.5.5.jar",
          "size": 812431,
          "sha512": "4c853ed36f012fccdba16f747e67951a4494f8e4e330988225b7ed9a3c17f84d1e245bfcce7e6e38e59322e49c0c7ee169e113459b92bf49a9e36fdd1bbbf9bd",
          "sha256": "05d65b14c5b12c8918fa86b33292ee24b815b2e1e07b031bf50d3f44441d5021",
          "sha1": "5d9862ffca096687a70369f973d54a80f825d6cb",
          "md5": "afacbab81eeb272038381fcd75e45181"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.5.5"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.5"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.5.5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+b8f10be9b1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+b8f10be9b1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+b8f10be9b1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+b8f10be9b1"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+forge"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "6.0.8-289"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        }
      ],
      "files": [
        {
          "name": "vtil-forge-1.20.1-0.5.5.jar",
          "url": "vtil-forge-1.20.1-0.5.5.jar",
          "size": 812431,
          "sha512": "4c853ed36f012fccdba16f747e67951a4494f8e4e330988225b7ed9a3c17f84d1e245bfcce7e6e38e59322e49c0c7ee169e113459b92bf49a9e36fdd1bbbf9bd",
          "sha256": "05d65b14c5b12c8918fa86b33292ee24b815b2e1e07b031bf50d3f44441d5021",
          "sha1": "5d9862ffca096687a70369f973d54a80f825d6cb",
          "md5": "afacbab81eeb272038381fcd75e45181"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.5.5"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.5"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.5.5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-forge-1.20.1-0.5.5-sources.jar",
          "url": "vtil-forge-1.20.1-0.5.5-sources.jar",
          "size": 108184,
          "sha512": "c9d765ae0f0fffc4ee6a1b914f0fa46c915bd148d4ee54b21261cafae9b1faf1ad07cdeef1dfda2cceb2730669bcfb927d9da69ea343a704695d7da1e30be3ea",
          "sha256": "7940a82ab55ec01bb0a130907a97ce2848ceb6016e217dc1ea4b24c4f0539047",
          "sha1": "0d046a91caffa7109d563946d0ba37cca6a0eab9",
          "md5": "c140751ffb8f7835a2dab7e5c95e5367"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.5.5"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.5"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.5.5"
        }
      ]
    }
  ]
}
