{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vschunkloader",
    "module": "VSChunkLoader-forge-1.20.1",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-forge",
          "version": {
            "requires": "2.3.0-beta.12"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "VSChunkLoader-forge-1.20.1-1.5.0.jar",
          "url": "VSChunkLoader-forge-1.20.1-1.5.0.jar",
          "size": 1615073,
          "sha512": "857a91c261d83f800fead60939a88cb46e828835ebc7725495c96ec229eb154083c3510a2c6ae316752bb341b6f5707ad1c3f71374afb4355564e4bb183f0b41",
          "sha256": "b150c7e7dc24a38865bb51cb872fe4cbb102752b14668beeed612d0640228728",
          "sha1": "fb92a8b9f030893c6bbcbb04058eddcf33837026",
          "md5": "bebc41f5c788acd6af2237f9c184b860"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "forge",
          "version": "1.5.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "VSChunkLoader-forge-1.20.1",
          "version": "1.5.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader",
          "version": "1.5.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader-forge-1.20.1",
          "version": "1.5.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api-game",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-forge",
          "version": {
            "requires": "2.3.0-beta.12"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-forge-1.20.1",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+forge"
          }
        }
      ],
      "files": [
        {
          "name": "VSChunkLoader-forge-1.20.1-1.5.0.jar",
          "url": "VSChunkLoader-forge-1.20.1-1.5.0.jar",
          "size": 1615073,
          "sha512": "857a91c261d83f800fead60939a88cb46e828835ebc7725495c96ec229eb154083c3510a2c6ae316752bb341b6f5707ad1c3f71374afb4355564e4bb183f0b41",
          "sha256": "b150c7e7dc24a38865bb51cb872fe4cbb102752b14668beeed612d0640228728",
          "sha1": "fb92a8b9f030893c6bbcbb04058eddcf33837026",
          "md5": "bebc41f5c788acd6af2237f9c184b860"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "forge",
          "version": "1.5.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "VSChunkLoader-forge-1.20.1",
          "version": "1.5.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader",
          "version": "1.5.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader-forge-1.20.1",
          "version": "1.5.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VSChunkLoader-forge-1.20.1-1.5.0-sources.jar",
          "url": "VSChunkLoader-forge-1.20.1-1.5.0-sources.jar",
          "size": 141568,
          "sha512": "dcf0a0060cc3b438e0558ae8ff0b33c5f2b29b8cd84ac21fd3ad397f097d315484e038915b5ce8509ab1c7382bb487ec2683680f340c0da8dfcb783f2483cd82",
          "sha256": "ea1037bb4df7999d269b67bebdddf5e8ab5aec5f6f454f7562947b698f23bd8f",
          "sha1": "042b7748de17f801aa51784eb7d1d891821a3a45",
          "md5": "6a105a3c9fcb27465e2d48ea6f4a0b12"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "forge",
          "version": "1.5.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "VSChunkLoader-forge-1.20.1",
          "version": "1.5.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader",
          "version": "1.5.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader-forge-1.20.1",
          "version": "1.5.0"
        }
      ]
    }
  ]
}
