{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-common-1.20.1",
    "version": "0.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.0+99a5c6e40f"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.5.4.jar",
          "url": "vtil-common-1.20.1-0.5.4.jar",
          "size": 167283,
          "sha512": "9c31454a8f51d761a5c61f8f8c9a153aed3603a7cf7542da5dbb871348f96464d5c3af3ab1cbd1077e7e533504583e6a52179152602ff2e9e908f4a0c7bf104a",
          "sha256": "659d3ed33c799277bf22d36467c4b2f883a3d587b21072649a92c94ba6b844ff",
          "sha1": "224d133ea4a2c4fedbd4772bdf1986042faf4a5c",
          "md5": "473b112652c7b00f963de848f5d035bd"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.4"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.5.4"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.5.4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+b8f10be9b1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+b8f10be9b1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+b8f10be9b1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+b8f10be9b1"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.0+99a5c6e40f"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.5.4.jar",
          "url": "vtil-common-1.20.1-0.5.4.jar",
          "size": 167283,
          "sha512": "9c31454a8f51d761a5c61f8f8c9a153aed3603a7cf7542da5dbb871348f96464d5c3af3ab1cbd1077e7e533504583e6a52179152602ff2e9e908f4a0c7bf104a",
          "sha256": "659d3ed33c799277bf22d36467c4b2f883a3d587b21072649a92c94ba6b844ff",
          "sha1": "224d133ea4a2c4fedbd4772bdf1986042faf4a5c",
          "md5": "473b112652c7b00f963de848f5d035bd"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.4"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.5.4"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.5.4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-common-1.20.1-0.5.4-sources.jar",
          "url": "vtil-common-1.20.1-0.5.4-sources.jar",
          "size": 98002,
          "sha512": "431326a2c5d84114dd93e25bb8ec8367d421c856d5bd51e92547ce10b99171cf9d95c3c096c2f9fc0e28492ac5a4b8e9a63742ffbb28704233f8198ab1287c96",
          "sha256": "de16936fb9aa75d93e0836f3df36e8de7ac52863515d1fc19a5fe0c03c5c9a5a",
          "sha1": "66920c07c6dce4e37972bf6d8962e9ce2526d88c",
          "md5": "0aaa5a679dc4df449a2b1e3d021d3b2e"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.4"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.5.4"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.5.4"
        }
      ]
    }
  ]
}
