{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-forge-1.20.1",
    "version": "0.5.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-forge-1.20.1-0.5.10.jar",
          "url": "vtil-forge-1.20.1-0.5.10.jar",
          "size": 816542,
          "sha512": "9a3d7e30cdb4511609928e1c854b495eb8c09e8b93ab8d884c97a7dcab45c4e4f23201b3e5374cec4d374e60128bf440cd47a968c0ea4c53b312bf11abd40e5f",
          "sha256": "5912d9b25c715f5c2785faab7110204a82d239fc0a583f3a120e8afd60a57251",
          "sha1": "cf279fd368f64cd2d023d6cf3d94cfacdcf8439e",
          "md5": "092e6bfb82703a5928bbad1b377306c1"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.5.10"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.5.10"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.10"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+forge"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "6.0.8-289"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        }
      ],
      "files": [
        {
          "name": "vtil-forge-1.20.1-0.5.10.jar",
          "url": "vtil-forge-1.20.1-0.5.10.jar",
          "size": 816542,
          "sha512": "9a3d7e30cdb4511609928e1c854b495eb8c09e8b93ab8d884c97a7dcab45c4e4f23201b3e5374cec4d374e60128bf440cd47a968c0ea4c53b312bf11abd40e5f",
          "sha256": "5912d9b25c715f5c2785faab7110204a82d239fc0a583f3a120e8afd60a57251",
          "sha1": "cf279fd368f64cd2d023d6cf3d94cfacdcf8439e",
          "md5": "092e6bfb82703a5928bbad1b377306c1"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.5.10"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.5.10"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.10"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-forge-1.20.1-0.5.10-sources.jar",
          "url": "vtil-forge-1.20.1-0.5.10-sources.jar",
          "size": 109609,
          "sha512": "04af54143a9e5ca43a21ee901c725b2ff7d656b595162fc54780536710b4f531c27e6c9142ec17d47bf8ee51e59b0bb63c474a91e3983717ef05dbef2faec957",
          "sha256": "a3fc6ccd941f2fecc8108dbec556756e4cd015f277e349906882b3da02f49d93",
          "sha1": "3221752568dac13c80b69b1d816fec1aee1cfad1",
          "md5": "e60b500d2e347587873c772e2c1ee75f"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.5.10"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.5.10"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.10"
        }
      ]
    }
  ]
}
