{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-common-1.20.1",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.3.0-beta.11"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.3.0.jar",
          "url": "vtil-common-1.20.1-0.3.0.jar",
          "size": 130127,
          "sha512": "c29f01538247e396a7cef59a0f91c6e23d1b4c0ddb6c89b90e8ef76f3ffba3781c95e00a299a10fd52ce6cf90feb250473e9e78b50ed5d52384b441f430c67c1",
          "sha256": "4ad90787d7d5f3b25c4f4a29f779d219e42227d11c74b437e4565871c82418d1",
          "sha1": "677b0c13008a564658868ec16603b3d4be60b37d",
          "md5": "3061c1048c8020ec8e4e0f1bd05f8017"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.3.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api-game",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.3.0-beta.11"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.3.0.jar",
          "url": "vtil-common-1.20.1-0.3.0.jar",
          "size": 130127,
          "sha512": "c29f01538247e396a7cef59a0f91c6e23d1b4c0ddb6c89b90e8ef76f3ffba3781c95e00a299a10fd52ce6cf90feb250473e9e78b50ed5d52384b441f430c67c1",
          "sha256": "4ad90787d7d5f3b25c4f4a29f779d219e42227d11c74b437e4565871c82418d1",
          "sha1": "677b0c13008a564658868ec16603b3d4be60b37d",
          "md5": "3061c1048c8020ec8e4e0f1bd05f8017"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.3.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-common-1.20.1-0.3.0-sources.jar",
          "url": "vtil-common-1.20.1-0.3.0-sources.jar",
          "size": 80769,
          "sha512": "a5787a8f1c31e84f178d9297a8d939d5b48902ca533c84083c9954a0548ff05332e570f79f5e7e871878179bbe6c671c30cbcce0d248b0fe53657cacbe6fb09f",
          "sha256": "b0354a886bc5b76408a3a0477b8ead66c7d94b191559ca507c795114a7abdb73",
          "sha1": "1bccd480bdb7fc977fb8220be4e8f95005ce60ff",
          "md5": "49d0d653444253ca847d92e878095e39"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.3.0"
        }
      ]
    }
  ]
}
