{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vsplit",
    "module": "VSplit-fabric-1.20.1",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "VSplit-fabric-1.20.1-0.3.1.jar",
          "url": "VSplit-fabric-1.20.1-0.3.1.jar",
          "size": 1172401,
          "sha512": "dcc683756b4cccf7932e8d454d7133a7bb27ba42105485fb84b5c465e976dc6c1f8fd0411db80bf8336b6d4fb5ba40c56f6d461274864ddea29bd6f9fd51f31b",
          "sha256": "bdff5740519203dfdaf3f2839aa03a22093b6b3c11a1b9c9998558f0bd0470e8",
          "sha1": "bf2ce32849c6d0f2863b652774684653a7061418",
          "md5": "7ecf2f09fe8978db679e5d516bb76163"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-fabric-1.20.1",
          "version": "0.3.1"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.3.1"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "fabric",
          "version": "0.3.1"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-fabric-1.20.1",
          "version": "0.3.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.github.litermc.vsplit",
          "module": "VSplit-common-1.20.1",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-fabric-1.20.1",
          "version": {
            "requires": "0.4.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config",
          "version": {
            "requires": "6.4.90"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+fabric"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric",
          "version": {
            "requires": "6.0.8.0+build.1734-mc1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "VSplit-fabric-1.20.1-0.3.1.jar",
          "url": "VSplit-fabric-1.20.1-0.3.1.jar",
          "size": 1172401,
          "sha512": "dcc683756b4cccf7932e8d454d7133a7bb27ba42105485fb84b5c465e976dc6c1f8fd0411db80bf8336b6d4fb5ba40c56f6d461274864ddea29bd6f9fd51f31b",
          "sha256": "bdff5740519203dfdaf3f2839aa03a22093b6b3c11a1b9c9998558f0bd0470e8",
          "sha1": "bf2ce32849c6d0f2863b652774684653a7061418",
          "md5": "7ecf2f09fe8978db679e5d516bb76163"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-fabric-1.20.1",
          "version": "0.3.1"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.3.1"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "fabric",
          "version": "0.3.1"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-fabric-1.20.1",
          "version": "0.3.1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VSplit-fabric-1.20.1-0.3.1-sources.jar",
          "url": "VSplit-fabric-1.20.1-0.3.1-sources.jar",
          "size": 148782,
          "sha512": "f36fdfdb3f09974b2a922aead3573200c13872aff6605f8f20a8f41cae1eb773046a558f01c4768e3900f1d8e030e40d63f4b1eb972dbd967371e94ab0056790",
          "sha256": "d3d5dea8978ed7fc4426ab11426bc3adf993170ccf724c0c545cc3602ba42d6a",
          "sha1": "880d1c6538fd2c41eac52fb543ba79693445a350",
          "md5": "697b7e2003e2e61bc65315140a5ddd5f"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-fabric-1.20.1",
          "version": "0.3.1"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.3.1"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "fabric",
          "version": "0.3.1"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-fabric-1.20.1",
          "version": "0.3.1"
        }
      ]
    }
  ]
}
