{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-forge-1.20.1",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-forge-1.20.1-0.5.1.jar",
          "url": "vtil-forge-1.20.1-0.5.1.jar",
          "size": 807367,
          "sha512": "c758b80fb3d35f207e1531a2247ed4b0a5130dfebdb55b4462b38d69a02886e597dcc11e3880889b8d2903badf37d026845eb79baa3520f78439afb8a87d430a",
          "sha256": "c11d6e873f93f2e06a7b4051171a2fa2395981cedcecca957194d9505b79557b",
          "sha1": "336bf75cad55e1d776482c0a1b11bebff2880394",
          "md5": "51e3c7213f4e31590ea2551d78811827"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.5.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.5.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+8a3bf60955"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+8a3bf60955"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+8a3bf60955"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+8a3bf60955"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+forge"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "6.0.8-289"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        }
      ],
      "files": [
        {
          "name": "vtil-forge-1.20.1-0.5.1.jar",
          "url": "vtil-forge-1.20.1-0.5.1.jar",
          "size": 807367,
          "sha512": "c758b80fb3d35f207e1531a2247ed4b0a5130dfebdb55b4462b38d69a02886e597dcc11e3880889b8d2903badf37d026845eb79baa3520f78439afb8a87d430a",
          "sha256": "c11d6e873f93f2e06a7b4051171a2fa2395981cedcecca957194d9505b79557b",
          "sha1": "336bf75cad55e1d776482c0a1b11bebff2880394",
          "md5": "51e3c7213f4e31590ea2551d78811827"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.5.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.5.1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-forge-1.20.1-0.5.1-sources.jar",
          "url": "vtil-forge-1.20.1-0.5.1-sources.jar",
          "size": 107117,
          "sha512": "6c2efa3f87dd7c503406965ff81af0581dc7769fd835ebed127549ffc74504a4363c9d037f615c94a61777e618e9812b4ec01d7f9564fb27b0951ddf189bca65",
          "sha256": "10bf1824e34a44a622ac5187011c404a69c83c5b0ec616e3282396fcd22a69e2",
          "sha1": "aea68fe4176bf285f9f88b79ac7378264ec1a1ac",
          "md5": "32a0d8d7683023704eb90a6d830d898b"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.5.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.5.1"
        }
      ]
    }
  ]
}
