{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "Vtil-common-1.20.1",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.3.0-beta.11"
          }
        }
      ],
      "files": [
        {
          "name": "Vtil-common-1.20.1-0.2.0.jar",
          "url": "Vtil-common-1.20.1-0.2.0.jar",
          "size": 107228,
          "sha512": "882fb231d9b94403608ac286cf57afe0573ee56e451bfae8f9682dc14e19af1cf6edcdba08ad15d540a27491f578cee93c2e3faa95c1f83aa72c15abdef65883",
          "sha256": "66be7785adbf882b1456cf7b265b421ce5b9da526f38ff1b471347846f5f99c5",
          "sha1": "1309848ecfe598a02f6b36fa11e4e71c9a581158",
          "md5": "838d38052837f2a44941a50acb698f8c"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "Vtil-common-1.20.1",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.2.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api-game",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.3.0-beta.11"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "Vtil-common-1.20.1-0.2.0.jar",
          "url": "Vtil-common-1.20.1-0.2.0.jar",
          "size": 107228,
          "sha512": "882fb231d9b94403608ac286cf57afe0573ee56e451bfae8f9682dc14e19af1cf6edcdba08ad15d540a27491f578cee93c2e3faa95c1f83aa72c15abdef65883",
          "sha256": "66be7785adbf882b1456cf7b265b421ce5b9da526f38ff1b471347846f5f99c5",
          "sha1": "1309848ecfe598a02f6b36fa11e4e71c9a581158",
          "md5": "838d38052837f2a44941a50acb698f8c"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "Vtil-common-1.20.1",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.2.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Vtil-common-1.20.1-0.2.0-sources.jar",
          "url": "Vtil-common-1.20.1-0.2.0-sources.jar",
          "size": 70133,
          "sha512": "a7449f114930473fd9ea6cf0c60a0798aac6377bd5d2d27874e67440eac9b557e1a636ab7b68708a881dec22e3ac711d5ab958e35f7e4a6c1551cdecd862c997",
          "sha256": "7cb427ed997c72be6ba6fbc8f377b44234072b2cd0cd4665585892d9562abe93",
          "sha1": "67794366721f4fe388a193056bc903b7eb3092b0",
          "md5": "24e95e48484c840b079cb57bccde93a5"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "Vtil-common-1.20.1",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.2.0"
        }
      ]
    }
  ]
}
