{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vsplit",
    "module": "VSplit-common-1.20.1",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.3.0-beta.11"
          }
        }
      ],
      "files": [
        {
          "name": "VSplit-common-1.20.1-0.3.0.jar",
          "url": "VSplit-common-1.20.1-0.3.0.jar",
          "size": 185182,
          "sha512": "e16a2f0dadeb53f3241c9b8cfa55d9f55ba457f38378205a4f140ab99139299cca3b0421b40dc797350be8bbf0823a6e3cb6178c59043f6a170a793a1118c555",
          "sha256": "6dd81d5a9778d5fdedffb8853b72e5863f02246c0bb2d836cc64229e260fc651",
          "sha1": "ee335e004baf54a39fe8fb25f832bb66c2dd1817",
          "md5": "3b58862b954e452bdd775a3c63088faf"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-common-1.20.1",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "common",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-common-1.20.1",
          "version": "0.3.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api-game",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.3.0-beta.11"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-common-1.20.1",
          "version": {
            "requires": "0.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "VSplit-common-1.20.1-0.3.0.jar",
          "url": "VSplit-common-1.20.1-0.3.0.jar",
          "size": 185182,
          "sha512": "e16a2f0dadeb53f3241c9b8cfa55d9f55ba457f38378205a4f140ab99139299cca3b0421b40dc797350be8bbf0823a6e3cb6178c59043f6a170a793a1118c555",
          "sha256": "6dd81d5a9778d5fdedffb8853b72e5863f02246c0bb2d836cc64229e260fc651",
          "sha1": "ee335e004baf54a39fe8fb25f832bb66c2dd1817",
          "md5": "3b58862b954e452bdd775a3c63088faf"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-common-1.20.1",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "common",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-common-1.20.1",
          "version": "0.3.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VSplit-common-1.20.1-0.3.0-sources.jar",
          "url": "VSplit-common-1.20.1-0.3.0-sources.jar",
          "size": 138006,
          "sha512": "464bf837602461bcd229d26eea831c726577a2ae4302ed516ef95db44f2ac31974d045cdf09a819c4b81b89df604c2715f1cb5886bf24658a481ca8bc5d2d458",
          "sha256": "427488098a18efc5c6407c5be74bb0ff78d31660338fae2f730a487c76d68ebd",
          "sha1": "954138ce9e0fa243ac16722480a6a5230b201939",
          "md5": "fdbc9096a2e9a3bae511b1fb2daabf6d"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-common-1.20.1",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "common",
          "version": "0.3.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-common-1.20.1",
          "version": "0.3.0"
        }
      ]
    }
  ]
}
