{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-fabric-1.20.1",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.5.0.jar",
          "url": "vtil-fabric-1.20.1-0.5.0.jar",
          "size": 586435,
          "sha512": "945d8fea84e81dd003dfa1dd1e04f1647e0041134f30b7d109753578ebaca6b7d1d9239d28dcc15d68ca9b6b74057c133e33627d0f31a207e56511b07c1df055",
          "sha256": "032f3fce243b84cef44c591a5b7dc647af66c532c56739717dbeeaf480e6785a",
          "sha1": "77e5462a172547c39c0103804b5d93dce97bde63",
          "md5": "853764d55b7a10c41f62d5cbee840696"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.5.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.5.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+3434464932"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+3434464932"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+3434464932"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+3434464932"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-common-1.20.1",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config",
          "version": {
            "requires": "6.4.90"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+fabric"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric",
          "version": {
            "requires": "6.0.8.0+build.1734-mc1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.5.0.jar",
          "url": "vtil-fabric-1.20.1-0.5.0.jar",
          "size": 586435,
          "sha512": "945d8fea84e81dd003dfa1dd1e04f1647e0041134f30b7d109753578ebaca6b7d1d9239d28dcc15d68ca9b6b74057c133e33627d0f31a207e56511b07c1df055",
          "sha256": "032f3fce243b84cef44c591a5b7dc647af66c532c56739717dbeeaf480e6785a",
          "sha1": "77e5462a172547c39c0103804b5d93dce97bde63",
          "md5": "853764d55b7a10c41f62d5cbee840696"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.5.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.5.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.5.0-sources.jar",
          "url": "vtil-fabric-1.20.1-0.5.0-sources.jar",
          "size": 106013,
          "sha512": "9b2ede5368014d21511dc92ea3461f4fe3d950273c32a8512bdab9783a9c03f2543f6880183b751494e10087e7f79d6a6fbb98fc4de778b6323d2698e23d1ee3",
          "sha256": "11278591ee6822eb390548c67fbcf15190e79867d66b8f952193820006f78e4f",
          "sha1": "1e864c0dcef74466b82d2039b82cea22381f62df",
          "md5": "709d7aa5253cafb0c98a2aab59b7de7b"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.5.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.5.0"
        }
      ]
    }
  ]
}
