{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-fabric-1.20.1",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.4.4.jar",
          "url": "vtil-fabric-1.20.1-0.4.4.jar",
          "size": 585110,
          "sha512": "2dc6e08b4960e7392389188e4677d3245690e2901f1b7a6d34f212786c783ee16292b1f96b099cb9dbe0cad72ee11a3c092e822959f4e24e68948772ee11dfc1",
          "sha256": "fdd12f674cdcdfa06f251a79bf38cbf4d001384003e025d4cfca27b1c15e823f",
          "sha1": "1cb51aae0ddb56fd2dab5eab12e44669cbecf7de",
          "md5": "7eeea93310179a4047d5ece03c2251de"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.4.4"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.4.4"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.4.4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-common-1.20.1",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config",
          "version": {
            "requires": "6.4.90"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+fabric"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric",
          "version": {
            "requires": "6.0.8.0+build.1734-mc1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.4.4.jar",
          "url": "vtil-fabric-1.20.1-0.4.4.jar",
          "size": 585110,
          "sha512": "2dc6e08b4960e7392389188e4677d3245690e2901f1b7a6d34f212786c783ee16292b1f96b099cb9dbe0cad72ee11a3c092e822959f4e24e68948772ee11dfc1",
          "sha256": "fdd12f674cdcdfa06f251a79bf38cbf4d001384003e025d4cfca27b1c15e823f",
          "sha1": "1cb51aae0ddb56fd2dab5eab12e44669cbecf7de",
          "md5": "7eeea93310179a4047d5ece03c2251de"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.4.4"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.4.4"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.4.4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.4.4-sources.jar",
          "url": "vtil-fabric-1.20.1-0.4.4-sources.jar",
          "size": 103347,
          "sha512": "a19195e6ed752141d3c275a39a5880b56fa1fc8aaab053ecc71c69023d2f107792b670cad90a86425c270e0aa97c5456cd700f055d5b0b80deecf76bdb69f9fa",
          "sha256": "769f494af93470928f9f5810cfad81da16918a1c3f5b74fbab861f0c6912c929",
          "sha1": "3a565f3e2a24de1038d645fd1f5a58607d08717d",
          "md5": "73da231f97d5187c955b306f89e8c325"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.4.4"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.4.4"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.4.4"
        }
      ]
    }
  ]
}
