{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vschunkloader",
    "module": "VSChunkLoader-fabric-1.20.1",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "VSChunkLoader-fabric-1.20.1-1.5.0.jar",
          "url": "VSChunkLoader-fabric-1.20.1-1.5.0.jar",
          "size": 1175230,
          "sha512": "8fa858f7f126b94563c02658751bdbb16417a5386f0fe36fa662db643448ba139f61b5d69c0d244c967c857b23d251dd3b9858c29a51ba681b345b64aa68f41e",
          "sha256": "59deda8ac8e79325c1ebdb2c8d774bc58fd1ced802fdbadb9278f02389e6b963",
          "sha1": "5c47cc91430d1898fd058e64cd96496434976bc6",
          "md5": "72d90aaa0cc67f7a1b3810f6a4d16117"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "VSChunkLoader-fabric-1.20.1",
          "version": "1.5.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "fabric",
          "version": "1.5.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader-fabric-1.20.1",
          "version": "1.5.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader",
          "version": "1.5.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "module": "VSChunkLoader-common-1.20.1",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-fabric-1.20.1",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config",
          "version": {
            "requires": "6.4.90"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+fabric"
          }
        }
      ],
      "files": [
        {
          "name": "VSChunkLoader-fabric-1.20.1-1.5.0.jar",
          "url": "VSChunkLoader-fabric-1.20.1-1.5.0.jar",
          "size": 1175230,
          "sha512": "8fa858f7f126b94563c02658751bdbb16417a5386f0fe36fa662db643448ba139f61b5d69c0d244c967c857b23d251dd3b9858c29a51ba681b345b64aa68f41e",
          "sha256": "59deda8ac8e79325c1ebdb2c8d774bc58fd1ced802fdbadb9278f02389e6b963",
          "sha1": "5c47cc91430d1898fd058e64cd96496434976bc6",
          "md5": "72d90aaa0cc67f7a1b3810f6a4d16117"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "VSChunkLoader-fabric-1.20.1",
          "version": "1.5.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "fabric",
          "version": "1.5.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader-fabric-1.20.1",
          "version": "1.5.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader",
          "version": "1.5.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VSChunkLoader-fabric-1.20.1-1.5.0-sources.jar",
          "url": "VSChunkLoader-fabric-1.20.1-1.5.0-sources.jar",
          "size": 140951,
          "sha512": "fe355dcaff5b6338701d166eb7fab3c23e6489f123815c434200eb4d2593b30aff3961c9fbac2ebdc8f54ad13ce040098642f76f7e887ec05cced3aa87aa7095",
          "sha256": "d460b53653c7fa1e4cc019f8c58fd1f10502cf9c8287f4b37e794a4d2dc431d5",
          "sha1": "992e160b6af174aa431cdbab5c4e7a39da11d4bc",
          "md5": "bc9a7cd39b2e59f02b4664e1ef180025"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "VSChunkLoader-fabric-1.20.1",
          "version": "1.5.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "fabric",
          "version": "1.5.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader-fabric-1.20.1",
          "version": "1.5.0"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader",
          "version": "1.5.0"
        }
      ]
    }
  ]
}
