{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-common-1.20.1",
    "version": "0.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.3+6faf19387f"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.5.6.jar",
          "url": "vtil-common-1.20.1-0.5.6.jar",
          "size": 171099,
          "sha512": "54b8a36002dcc1c172f3a55104af4a4aba5ae09cf77269b8fe5697e23aa6265f01f753e6f4ae5bed6714658402217c94359b0ce96395397b362d4766402d091b",
          "sha256": "fc9a4370bbc817505834d82a6a058d1d9e00ce0d5860d2de91ede15da0d780a1",
          "sha1": "6900b1bccad1265e15e4d18c6105a1a195482561",
          "md5": "986e284a1ff3db3ed88bc60ae2d5cd9d"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.6"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.5.6"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.5.6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.3+6faf19387f"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.5.6.jar",
          "url": "vtil-common-1.20.1-0.5.6.jar",
          "size": 171099,
          "sha512": "54b8a36002dcc1c172f3a55104af4a4aba5ae09cf77269b8fe5697e23aa6265f01f753e6f4ae5bed6714658402217c94359b0ce96395397b362d4766402d091b",
          "sha256": "fc9a4370bbc817505834d82a6a058d1d9e00ce0d5860d2de91ede15da0d780a1",
          "sha1": "6900b1bccad1265e15e4d18c6105a1a195482561",
          "md5": "986e284a1ff3db3ed88bc60ae2d5cd9d"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.6"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.5.6"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.5.6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-common-1.20.1-0.5.6-sources.jar",
          "url": "vtil-common-1.20.1-0.5.6-sources.jar",
          "size": 99252,
          "sha512": "794bcb4ad181c013ee35b2af7d7139a738864238d468c51896c95c76eb8b032620bb6fe62292f08479f091811bada1dd49a5fd8699f30f7927e85a1b099bc96e",
          "sha256": "201df8695628a287d546d06bc167d8dd7ac6580c7491824c4ad52b0e7490c118",
          "sha1": "4e13e9ff1152635921ede2fcc17312923ec2992f",
          "md5": "a774bdbaa72b4c2259824017e7540a95"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.6"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.5.6"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.5.6"
        }
      ]
    }
  ]
}
