{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vsplit",
    "module": "VSplit-fabric-1.20.1",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "VSplit-fabric-1.20.1-0.2.0.jar",
          "url": "VSplit-fabric-1.20.1-0.2.0.jar",
          "size": 1147103,
          "sha512": "8f3e5322b1c08b718349623ca65b3a23fbbc2129f7a43098f1fccc0b18c581a0ed468fe983e2b02a8c3128f8b8ecca542e66fee22888a7a412e2fb9d8414dd6f",
          "sha256": "d2d1d0a6eee41db09d928ce558dc08d3fb73590aff89ae820db2cea0497a271e",
          "sha1": "249bb903dacc8904d9f0c60fe38b2b83ea670471",
          "md5": "fde78515a97a36b7fcf24f5e4da0409e"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-fabric-1.20.1",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "fabric",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-fabric-1.20.1",
          "version": "0.2.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.github.litermc.vsplit",
          "module": "VSplit-common-1.20.1",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-fabric-1.20.1",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config",
          "version": {
            "requires": "6.4.90"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+fabric"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric",
          "version": {
            "requires": "6.0.8.0+build.1734-mc1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "VSplit-fabric-1.20.1-0.2.0.jar",
          "url": "VSplit-fabric-1.20.1-0.2.0.jar",
          "size": 1147103,
          "sha512": "8f3e5322b1c08b718349623ca65b3a23fbbc2129f7a43098f1fccc0b18c581a0ed468fe983e2b02a8c3128f8b8ecca542e66fee22888a7a412e2fb9d8414dd6f",
          "sha256": "d2d1d0a6eee41db09d928ce558dc08d3fb73590aff89ae820db2cea0497a271e",
          "sha1": "249bb903dacc8904d9f0c60fe38b2b83ea670471",
          "md5": "fde78515a97a36b7fcf24f5e4da0409e"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-fabric-1.20.1",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "fabric",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-fabric-1.20.1",
          "version": "0.2.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VSplit-fabric-1.20.1-0.2.0-sources.jar",
          "url": "VSplit-fabric-1.20.1-0.2.0-sources.jar",
          "size": 141291,
          "sha512": "96558d752c9a996b6502f4a2bca2b903631d9be15359ec73463c834a9917747bca770949854322cc41c7daac3a6a1ec2ee755b570d0b7f74a3898e9e30147d4e",
          "sha256": "627ee7d6d9dec8ce941c8d52b44acab9b44c617443bc98ca331e6f12489a1fa3",
          "sha1": "b3a5e3039e3e8528dcf9599859f3ebabcfb29a7b",
          "md5": "5933fdbb0ce0e045da0cf5cfb36ecaf9"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-fabric-1.20.1",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "fabric",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-fabric-1.20.1",
          "version": "0.2.0"
        }
      ]
    }
  ]
}
