{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "Vtil-forge-1.20.1",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-forge",
          "version": {
            "requires": "2.3.0-beta.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "Vtil-forge-1.20.1-0.2.0.jar",
          "url": "Vtil-forge-1.20.1-0.2.0.jar",
          "size": 1255349,
          "sha512": "24c13c702b6558efb9cf3fe692b29f57112babc3765315b90e1d36c6858a21eafa8a7d3d069206d1db83f9da047774813db3155b40adea3f1795b6222d563fc1",
          "sha256": "fdab13fbc40c218a415b69e35c57c527d9acc9defcab6245cbe4a514ef34dadd",
          "sha1": "328f310e9bd8ceb89bce94c8c4b1f361fb390b9d",
          "md5": "55b2353dd3d92cbc32601d5fbde22cd7"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "Vtil-forge-1.20.1",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.2.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api-game",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-forge",
          "version": {
            "requires": "2.3.0-beta.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+forge"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "6.0.8-289"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        }
      ],
      "files": [
        {
          "name": "Vtil-forge-1.20.1-0.2.0.jar",
          "url": "Vtil-forge-1.20.1-0.2.0.jar",
          "size": 1255349,
          "sha512": "24c13c702b6558efb9cf3fe692b29f57112babc3765315b90e1d36c6858a21eafa8a7d3d069206d1db83f9da047774813db3155b40adea3f1795b6222d563fc1",
          "sha256": "fdab13fbc40c218a415b69e35c57c527d9acc9defcab6245cbe4a514ef34dadd",
          "sha1": "328f310e9bd8ceb89bce94c8c4b1f361fb390b9d",
          "md5": "55b2353dd3d92cbc32601d5fbde22cd7"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "Vtil-forge-1.20.1",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.2.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Vtil-forge-1.20.1-0.2.0-sources.jar",
          "url": "Vtil-forge-1.20.1-0.2.0-sources.jar",
          "size": 79763,
          "sha512": "e3d620eea1504e6108a3fb09088d0d776f9c2f5254d7f07e8691713156df94eae2a39df8768f4661d23185a9e3b94e0e83ef0543d258ab56f16887ca537586da",
          "sha256": "d5c4e26a652b6a223cebcd3a7d5a51628e4e7e2e0221947d583b606b0d7122dc",
          "sha1": "7d76443e38cbe58ba0c8259bebf0242a89336f6a",
          "md5": "25ff5bde8e82e52bb7fb7760caec6eb4"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "Vtil-forge-1.20.1",
          "version": "0.2.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.2.0"
        }
      ]
    }
  ]
}
