{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-common-1.20.1",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.3.0-beta.11"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.4.1.jar",
          "url": "vtil-common-1.20.1-0.4.1.jar",
          "size": 151092,
          "sha512": "109df22b84ce8160a962e8a9adbbf0b496bd7d627aab072b0af14774a8d3f67e4464f9a39c70b0ec682734b0b98bb7f99e6351a5800a5e8e3df0004cd9b38f01",
          "sha256": "cbc9e3d899cd028be124dfb7d86eec823feaa7edb97723bd975256bec4062a12",
          "sha1": "9e33f503d57679cc82aee6b4f030121346eab4e7",
          "md5": "e8777eec0d0dd1c0d760d48948a4ee81"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.4.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.4.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.4.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api-game",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.3.0-beta.11"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.4.1.jar",
          "url": "vtil-common-1.20.1-0.4.1.jar",
          "size": 151092,
          "sha512": "109df22b84ce8160a962e8a9adbbf0b496bd7d627aab072b0af14774a8d3f67e4464f9a39c70b0ec682734b0b98bb7f99e6351a5800a5e8e3df0004cd9b38f01",
          "sha256": "cbc9e3d899cd028be124dfb7d86eec823feaa7edb97723bd975256bec4062a12",
          "sha1": "9e33f503d57679cc82aee6b4f030121346eab4e7",
          "md5": "e8777eec0d0dd1c0d760d48948a4ee81"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.4.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.4.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.4.1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-common-1.20.1-0.4.1-sources.jar",
          "url": "vtil-common-1.20.1-0.4.1-sources.jar",
          "size": 88696,
          "sha512": "20dc5eac3bc23d27f29f6797c3a79d28a11a3260cfb7daba9bf2eb5ec33f29def0ee1f3bbbd3fcdc2332a3b99f688eb436b41e55b4eb90f0adc6238da1ad2a9b",
          "sha256": "8572ebbead8704af2d44c93190342b2cd58a0048ae5f3ef12615732425c7cd68",
          "sha1": "dc7f1113bd40d7f0790801d9ccb361a4fcffc9a8",
          "md5": "004a0252c12a78db9f689bccf8e3405e"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.4.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.4.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.4.1"
        }
      ]
    }
  ]
}
