{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "Vtil-common-1.20.1",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.3.0-beta.11"
          }
        }
      ],
      "files": [
        {
          "name": "Vtil-common-1.20.1-0.1.0.jar",
          "url": "Vtil-common-1.20.1-0.1.0.jar",
          "size": 106250,
          "sha512": "dc0ba76811783561e08732e80af687a66840e68bba05b2a84c157cde6855fda544773a68e039b1a74216d67087d2943a87ed9c663a6578e4550df8ea049ca9e9",
          "sha256": "97e1ab59d67a31156aab423465b9843847d1112ac4189f6a6e368768ccecf961",
          "sha1": "2150506a2eafe79117eed7a9ca200494540e6d36",
          "md5": "06cba1811bf20e0def5947ca3a82f5aa"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "Vtil-common-1.20.1",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.1.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api-game",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.3.0-beta.11"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "Vtil-common-1.20.1-0.1.0.jar",
          "url": "Vtil-common-1.20.1-0.1.0.jar",
          "size": 106250,
          "sha512": "dc0ba76811783561e08732e80af687a66840e68bba05b2a84c157cde6855fda544773a68e039b1a74216d67087d2943a87ed9c663a6578e4550df8ea049ca9e9",
          "sha256": "97e1ab59d67a31156aab423465b9843847d1112ac4189f6a6e368768ccecf961",
          "sha1": "2150506a2eafe79117eed7a9ca200494540e6d36",
          "md5": "06cba1811bf20e0def5947ca3a82f5aa"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "Vtil-common-1.20.1",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.1.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Vtil-common-1.20.1-0.1.0-sources.jar",
          "url": "Vtil-common-1.20.1-0.1.0-sources.jar",
          "size": 69736,
          "sha512": "6d07cea7d9739cc868fafe130039a44bc87dc9ba4925a5f2e05cc861d63878134b7a4c1af084c845ea8c4d073444c1b0050615606dbc34bc1754b3a47dce844b",
          "sha256": "e761f997f0825ed30f8ae085bfedcc7efee868b365ef8beb4f7eefe9904a754e",
          "sha1": "3adc6bbdc724f9b909685cfbd324302795e1ccb5",
          "md5": "a6905d22e5a50894aea8837116979822"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "Vtil-common-1.20.1",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.1.0"
        }
      ]
    }
  ]
}
