{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "Vtil-common-1.20.1",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.3.0-beta.11"
          }
        }
      ],
      "files": [
        {
          "name": "Vtil-common-1.20.1-0.1.0.jar",
          "url": "Vtil-common-1.20.1-0.1.0.jar",
          "size": 107118,
          "sha512": "af5a23530cde9282351f93d457ec3068329258528d24824fc7aaee6deccf119fa10ee7ad4a289976bb857d96efdf72aa08315c22b186dd0c1ab31798e95f3cbe",
          "sha256": "49da70d6cd1ad5bd362c9fbac311a779453262a6c2206fd47958a56474045183",
          "sha1": "632b96a8f298550489b1631037743cbfcda2ae86",
          "md5": "bc376eed044c96c5850342ffdb2fbe55"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "Vtil-common-1.20.1",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.1.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api-game",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.3.0-beta.11"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "Vtil-common-1.20.1-0.1.0.jar",
          "url": "Vtil-common-1.20.1-0.1.0.jar",
          "size": 107118,
          "sha512": "af5a23530cde9282351f93d457ec3068329258528d24824fc7aaee6deccf119fa10ee7ad4a289976bb857d96efdf72aa08315c22b186dd0c1ab31798e95f3cbe",
          "sha256": "49da70d6cd1ad5bd362c9fbac311a779453262a6c2206fd47958a56474045183",
          "sha1": "632b96a8f298550489b1631037743cbfcda2ae86",
          "md5": "bc376eed044c96c5850342ffdb2fbe55"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "Vtil-common-1.20.1",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.1.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Vtil-common-1.20.1-0.1.0-sources.jar",
          "url": "Vtil-common-1.20.1-0.1.0-sources.jar",
          "size": 70082,
          "sha512": "3790530dc81e27fa3c7c3072403f0ffac80e2f2fdd0acf3262e82b15346962d2a56c68fb713592b82f5f72f8588426025abf437952c85e6ae6dcf60573e21f81",
          "sha256": "6fc92f7e3ee13a62024ec120381ca82f2c019bdcfd429f250ce443a5e7e01674",
          "sha1": "9a1dac07f21607c9d5c24cab614d4c5b59c3cc1d",
          "md5": "3960e015916d69e31e4cd2da3ce5b4cd"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "Vtil-common-1.20.1",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.1.0"
        }
      ]
    }
  ]
}
