{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vsplit",
    "module": "VSplit-forge-1.20.1",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-forge",
          "version": {
            "requires": "2.3.0-beta.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "VSplit-forge-1.20.1-0.1.4.jar",
          "url": "VSplit-forge-1.20.1-0.1.4.jar",
          "size": 1562856,
          "sha512": "f26659fa1d17840a03d6c27e6022a2146989cf75c0189056d500ca76e1b4cf3c8b10990999b4cabbf688a45f74bd4abbfabc6d9efdd956a74d583062d9ffc6f4",
          "sha256": "257627ee030e8fd1af909c561518d9169cf55f5ca35ab6958eceee1c92884d99",
          "sha1": "8fac223732039dd0b8600aed075026b2571b8ba5",
          "md5": "ec65806cbec7a1c0f784658f04943afb"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.1.4"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-forge-1.20.1",
          "version": "0.1.4"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "forge",
          "version": "0.1.4"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-forge-1.20.1",
          "version": "0.1.4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api-game",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-forge",
          "version": {
            "requires": "2.3.0-beta.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-forge-1.20.1",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+forge"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "6.0.8-289"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        }
      ],
      "files": [
        {
          "name": "VSplit-forge-1.20.1-0.1.4.jar",
          "url": "VSplit-forge-1.20.1-0.1.4.jar",
          "size": 1562856,
          "sha512": "f26659fa1d17840a03d6c27e6022a2146989cf75c0189056d500ca76e1b4cf3c8b10990999b4cabbf688a45f74bd4abbfabc6d9efdd956a74d583062d9ffc6f4",
          "sha256": "257627ee030e8fd1af909c561518d9169cf55f5ca35ab6958eceee1c92884d99",
          "sha1": "8fac223732039dd0b8600aed075026b2571b8ba5",
          "md5": "ec65806cbec7a1c0f784658f04943afb"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.1.4"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-forge-1.20.1",
          "version": "0.1.4"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "forge",
          "version": "0.1.4"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-forge-1.20.1",
          "version": "0.1.4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VSplit-forge-1.20.1-0.1.4-sources.jar",
          "url": "VSplit-forge-1.20.1-0.1.4-sources.jar",
          "size": 129577,
          "sha512": "48778691e1b34a379151d52c4b47514ffbff6264657d712f4480e0addd67bff5b2747b22ece0649478c77630ab5f05ef3283fcdc74632874eac75b06450d81eb",
          "sha256": "686fb3de632309a4de9f1ad0a346f2b1454fa45dc28d12e80303f8f364d6ebed",
          "sha1": "9d11c80b57733dd4449c0c2cea0bd75d53000fa6",
          "md5": "780c53402eb93c5b8f9bbbcdba84a847"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.1.4"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-forge-1.20.1",
          "version": "0.1.4"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "forge",
          "version": "0.1.4"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-forge-1.20.1",
          "version": "0.1.4"
        }
      ]
    }
  ]
}
