{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-fabric-1.20.1",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.3.1.jar",
          "url": "vtil-fabric-1.20.1-0.3.1.jar",
          "size": 556270,
          "sha512": "5adc44cd76d2c8377325cfea7cc239f3162ea37bd9b95d8e2c39b4a7f0108da0fd994510e5a59379db961fa525b79d8b8e5dcec71d426842fb379ac8ec5a8ee2",
          "sha256": "25609614d1995eff72cd928e3f9184fdb13ce66b9d4dbf68b9a3fdf03576fc2c",
          "sha1": "d3078becabbe8029f5b0f7052a0d16f08f93232b",
          "md5": "df23abc51a3fd78ac62a8b1f00e9bbbd"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.3.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.3.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.3.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-common-1.20.1",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config",
          "version": {
            "requires": "6.4.90"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+fabric"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric",
          "version": {
            "requires": "6.0.8.0+build.1734-mc1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.3.1.jar",
          "url": "vtil-fabric-1.20.1-0.3.1.jar",
          "size": 556270,
          "sha512": "5adc44cd76d2c8377325cfea7cc239f3162ea37bd9b95d8e2c39b4a7f0108da0fd994510e5a59379db961fa525b79d8b8e5dcec71d426842fb379ac8ec5a8ee2",
          "sha256": "25609614d1995eff72cd928e3f9184fdb13ce66b9d4dbf68b9a3fdf03576fc2c",
          "sha1": "d3078becabbe8029f5b0f7052a0d16f08f93232b",
          "md5": "df23abc51a3fd78ac62a8b1f00e9bbbd"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.3.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.3.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.3.1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.3.1-sources.jar",
          "url": "vtil-fabric-1.20.1-0.3.1-sources.jar",
          "size": 90633,
          "sha512": "1cbbcf67f74e72788ca4d63d91063a813a8a07f34391d180f607fe6c857725f7af0764005d8e4fa6174571451c11ca6a64089b046250b381c902883a3c4162d5",
          "sha256": "5f9fec36aa23aa30fe9858f5f446fdfd3d0e83cd187b26daf47c8b8f145ce3ce",
          "sha1": "ad861d24dd3472508beecd3d15e8b61a7cd072df",
          "md5": "2a70b82e46ca6d0016514c0e161258f9"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.3.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.3.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.3.1"
        }
      ]
    }
  ]
}
