{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "Vtil-forge-1.20.1",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-forge",
          "version": {
            "requires": "2.3.0-beta.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "Vtil-forge-1.20.1-0.2.2.jar",
          "url": "Vtil-forge-1.20.1-0.2.2.jar",
          "size": 1255304,
          "sha512": "ce89fe654aea18979699799befbdc46d0286dc6d76e8cc0cf40f176310b917f0c9469386e51509b06c8398d8baa1be80c49185c2c556a1cbcd6008ad88411c54",
          "sha256": "cc54661a780b5cbd6591d995138481ef75aeace13c643dd3ca50e97a6f2c5bbd",
          "sha1": "f1c2eed8b50a48c91e5fb4b7af9426afb5c0f144",
          "md5": "e512124ea034b50569a974903bd40958"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.2.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.2.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "Vtil-forge-1.20.1",
          "version": "0.2.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.2.2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api-game",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-forge",
          "version": {
            "requires": "2.3.0-beta.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+forge"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "6.0.8-289"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        }
      ],
      "files": [
        {
          "name": "Vtil-forge-1.20.1-0.2.2.jar",
          "url": "Vtil-forge-1.20.1-0.2.2.jar",
          "size": 1255304,
          "sha512": "ce89fe654aea18979699799befbdc46d0286dc6d76e8cc0cf40f176310b917f0c9469386e51509b06c8398d8baa1be80c49185c2c556a1cbcd6008ad88411c54",
          "sha256": "cc54661a780b5cbd6591d995138481ef75aeace13c643dd3ca50e97a6f2c5bbd",
          "sha1": "f1c2eed8b50a48c91e5fb4b7af9426afb5c0f144",
          "md5": "e512124ea034b50569a974903bd40958"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.2.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.2.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "Vtil-forge-1.20.1",
          "version": "0.2.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.2.2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Vtil-forge-1.20.1-0.2.2-sources.jar",
          "url": "Vtil-forge-1.20.1-0.2.2-sources.jar",
          "size": 79737,
          "sha512": "cd59bc6cd8cfcc43490d540f738e4edbee1b22b2c237f498a3ec728f3c336eb4026edcdd61a2e66ad8d8752f305222dfb92d752c148fa4884c6b828c3ddab846",
          "sha256": "d1ec060fdc44dddaa7cb5cbb9fb02fb6c51055c24b269c4e34fcf2d1385e0e60",
          "sha1": "9cce48a6bca883d8c3d2ffe6fa30116d53a17af7",
          "md5": "d6ede9aabb401e98b19a6b1080fd6eda"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.2.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-forge-1.20.1",
          "version": "0.2.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "Vtil-forge-1.20.1",
          "version": "0.2.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "forge",
          "version": "0.2.2"
        }
      ]
    }
  ]
}
