{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-common-1.20.1",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.0+9578397ff3"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.5.1.jar",
          "url": "vtil-common-1.20.1-0.5.1.jar",
          "size": 162257,
          "sha512": "09c181522323781df66d33902c416d8225ff1053d836affa54215a294f835c8bbbb0acf26dc647d76d06dfda1ed60b7149c66b57b71bbe3e7eab2241ba0e0146",
          "sha256": "5012b149b7566cb636830eef4f5d9f2d1f890e0d5e74e92a3a43c580499e06a9",
          "sha1": "e17f18f7eeb3aacc268e7e59a04705ec76467c9c",
          "md5": "51b9efaf3d8b1f524c132ab35449c30f"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.5.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.5.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+8a3bf60955"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+8a3bf60955"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+8a3bf60955"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+8a3bf60955"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.0+9578397ff3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.5.1.jar",
          "url": "vtil-common-1.20.1-0.5.1.jar",
          "size": 162257,
          "sha512": "09c181522323781df66d33902c416d8225ff1053d836affa54215a294f835c8bbbb0acf26dc647d76d06dfda1ed60b7149c66b57b71bbe3e7eab2241ba0e0146",
          "sha256": "5012b149b7566cb636830eef4f5d9f2d1f890e0d5e74e92a3a43c580499e06a9",
          "sha1": "e17f18f7eeb3aacc268e7e59a04705ec76467c9c",
          "md5": "51b9efaf3d8b1f524c132ab35449c30f"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.5.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.5.1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-common-1.20.1-0.5.1-sources.jar",
          "url": "vtil-common-1.20.1-0.5.1-sources.jar",
          "size": 96977,
          "sha512": "0d84e3cf3b924405e6b5f35f9a2dcf135949bec63abe51de8d9d9914b001e89a0274bc0e3aec7127373893caa3526a3ea8156e5693091afaf6c6972e230e73b2",
          "sha256": "595990025fc45cfde5bc8f0e4ce8fbaa1c2c69eaa6a69fbe2e546c2ab8414d5e",
          "sha1": "13bab9bb34b6ccaf74214a443e100f88b148c3fd",
          "md5": "217a464ec3503432d5f653bd92a7b01e"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.5.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.5.1"
        }
      ]
    }
  ]
}
