{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-common-1.20.1",
    "version": "0.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.0+99a5c6e40f"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.5.2.jar",
          "url": "vtil-common-1.20.1-0.5.2.jar",
          "size": 165181,
          "sha512": "959acdd027390ea521fac3d5d7c1335f1b21c3cad2716580827dbb4ca98ca454b24dfb039200c7380c306dffd8656ddb4fbe2dff90f49ec2b3302bfcebff086d",
          "sha256": "2bda9e695efc92c0a1ce2eedc38ea7ded28554c0626b2ad6f81b6b86de17c3cf",
          "sha1": "8e34270a155cc4b09bdaf8a339945df428960ab7",
          "md5": "1e3e21ce457f8a3381676bc21ecb314d"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.5.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.5.2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+b8f10be9b1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+b8f10be9b1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+b8f10be9b1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+b8f10be9b1"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.0+99a5c6e40f"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.5.2.jar",
          "url": "vtil-common-1.20.1-0.5.2.jar",
          "size": 165181,
          "sha512": "959acdd027390ea521fac3d5d7c1335f1b21c3cad2716580827dbb4ca98ca454b24dfb039200c7380c306dffd8656ddb4fbe2dff90f49ec2b3302bfcebff086d",
          "sha256": "2bda9e695efc92c0a1ce2eedc38ea7ded28554c0626b2ad6f81b6b86de17c3cf",
          "sha1": "8e34270a155cc4b09bdaf8a339945df428960ab7",
          "md5": "1e3e21ce457f8a3381676bc21ecb314d"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.5.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.5.2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-common-1.20.1-0.5.2-sources.jar",
          "url": "vtil-common-1.20.1-0.5.2-sources.jar",
          "size": 97050,
          "sha512": "a81629c25e36177e21d27615c605c161338f27074c3f3deff77c5979c27ef7e1bd3f97559f6ee3ef957f643d678acc787368accecec9ec3436fb5705f8d92898",
          "sha256": "bec69d90aa7e1fa2a79db1afe02b6faf9f1e5f4cb0cebf39bb09dc1a39333b03",
          "sha1": "417b59d998e75ac66522fff9b2d2da8cf8d1c005",
          "md5": "108648af41c0258461dd5ae1a414a214"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.5.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.5.2"
        }
      ]
    }
  ]
}
