{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vsplit",
    "module": "VSplit-common-1.20.1",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.11+c1e5b68ef8"
          }
        }
      ],
      "files": [
        {
          "name": "VSplit-common-1.20.1-0.4.0.jar",
          "url": "VSplit-common-1.20.1-0.4.0.jar",
          "size": 187109,
          "sha512": "44303b67f1f0510636e0d206bde0070224b71dc3410ab3fa12579cc9f5f60b602c3299cf469e697a53dd9e9a400c3e109e514a21bb59146db5c4a032474ea039",
          "sha256": "2adf90f6d2d50b42f78118b8bbb0599ac2d8f6432bb2def6352d8f9074dfa759",
          "sha1": "57065b39e4a86de6b1825079e96738162cb715a2",
          "md5": "9d882cd003387468607b2aee0f16a3d4"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.4.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-common-1.20.1",
          "version": "0.4.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "common",
          "version": "0.4.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-common-1.20.1",
          "version": "0.4.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.11+c1e5b68ef8"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-common-1.20.1",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "VSplit-common-1.20.1-0.4.0.jar",
          "url": "VSplit-common-1.20.1-0.4.0.jar",
          "size": 187109,
          "sha512": "44303b67f1f0510636e0d206bde0070224b71dc3410ab3fa12579cc9f5f60b602c3299cf469e697a53dd9e9a400c3e109e514a21bb59146db5c4a032474ea039",
          "sha256": "2adf90f6d2d50b42f78118b8bbb0599ac2d8f6432bb2def6352d8f9074dfa759",
          "sha1": "57065b39e4a86de6b1825079e96738162cb715a2",
          "md5": "9d882cd003387468607b2aee0f16a3d4"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.4.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-common-1.20.1",
          "version": "0.4.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "common",
          "version": "0.4.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-common-1.20.1",
          "version": "0.4.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VSplit-common-1.20.1-0.4.0-sources.jar",
          "url": "VSplit-common-1.20.1-0.4.0-sources.jar",
          "size": 139386,
          "sha512": "5b63f24e66d63321481ee70ff15f51ffb205c5a8b3463ce642faee895d8bf6fc950dc19185a83a02fb0a1cc429c08630f371f187b6b1471f03f13d392fafc126",
          "sha256": "8926a3c135c9e41aad332255ce078ad08b99daaa6354c9e6cde8096e5ca2418b",
          "sha1": "efa7824f0fc9a67b6c1bc509054e57218138c464",
          "md5": "68ebb69876655156db3467b7e00e4b2e"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.4.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-common-1.20.1",
          "version": "0.4.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "common",
          "version": "0.4.0"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-common-1.20.1",
          "version": "0.4.0"
        }
      ]
    }
  ]
}
