{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vsplit",
    "module": "VSplit-common-1.20.1",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.3.0-beta.11"
          }
        }
      ],
      "files": [
        {
          "name": "VSplit-common-1.20.1-0.1.3.jar",
          "url": "VSplit-common-1.20.1-0.1.3.jar",
          "size": 144010,
          "sha512": "34f4f11e9474100cb16cf1f0c8912f729fe0efc3eee99a91ed5714b3a9c398b8453fff39473c4e1a8ba319d21b08f8c97bf95b23597f09d7599e0f83d7599519",
          "sha256": "5bbc3f105a2f388fa0e0ff437f9d988f6949463228562d33c907777c279f46d9",
          "sha1": "110b69460a3e55a6fe2cf8094e520bbe8c457644",
          "md5": "7a1897041e6eb4477f8aaa3459c04fcd"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.1.3"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-common-1.20.1",
          "version": "0.1.3"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "common",
          "version": "0.1.3"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-common-1.20.1",
          "version": "0.1.3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api-game",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.3.0-beta.11"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-common-1.20.1",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "VSplit-common-1.20.1-0.1.3.jar",
          "url": "VSplit-common-1.20.1-0.1.3.jar",
          "size": 144010,
          "sha512": "34f4f11e9474100cb16cf1f0c8912f729fe0efc3eee99a91ed5714b3a9c398b8453fff39473c4e1a8ba319d21b08f8c97bf95b23597f09d7599e0f83d7599519",
          "sha256": "5bbc3f105a2f388fa0e0ff437f9d988f6949463228562d33c907777c279f46d9",
          "sha1": "110b69460a3e55a6fe2cf8094e520bbe8c457644",
          "md5": "7a1897041e6eb4477f8aaa3459c04fcd"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.1.3"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-common-1.20.1",
          "version": "0.1.3"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "common",
          "version": "0.1.3"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-common-1.20.1",
          "version": "0.1.3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VSplit-common-1.20.1-0.1.3-sources.jar",
          "url": "VSplit-common-1.20.1-0.1.3-sources.jar",
          "size": 118916,
          "sha512": "861ca4549598a1f344231f7e115ecb530ca3c62bbdd8df4fdaa849046eff3429d3a755149b4e226b23a78b0d00930616d2978f73504ed8d8be0d32ac7837df52",
          "sha256": "e5a28a81fead0432119644da6a2a60bee05f8d6527f4c055ef1802c22ffad466",
          "sha1": "596a7ebd084cb3c43cc94c3e893b6ab50fe0d35f",
          "md5": "66cf32f2d818f0a074c405cd002830eb"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.1.3"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-common-1.20.1",
          "version": "0.1.3"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "common",
          "version": "0.1.3"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-common-1.20.1",
          "version": "0.1.3"
        }
      ]
    }
  ]
}
