{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-common-1.20.1",
    "version": "0.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.3.0-beta.11"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.4.3.jar",
          "url": "vtil-common-1.20.1-0.4.3.jar",
          "size": 159605,
          "sha512": "9008439f34867bc7433757c39f17d603e483bb0c03ee46b6f890426b65c62a1384080cbb295c0a130b1e17f5f5c4cac7719adfe39c27bfc7deaaf9b635db5c00",
          "sha256": "c350e02db9693bc2391246476d5713be10d79a65cef3f6e9a8561a094255fa59",
          "sha1": "b61a215c124b52c200929695e912ca55a7960d6a",
          "md5": "2a6ab89b88f57203191e5ecb1acfc4f2"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.4.3"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.4.3"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.4.3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api-game",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+cf6990a85d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.3.0-beta.11"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.4.3.jar",
          "url": "vtil-common-1.20.1-0.4.3.jar",
          "size": 159605,
          "sha512": "9008439f34867bc7433757c39f17d603e483bb0c03ee46b6f890426b65c62a1384080cbb295c0a130b1e17f5f5c4cac7719adfe39c27bfc7deaaf9b635db5c00",
          "sha256": "c350e02db9693bc2391246476d5713be10d79a65cef3f6e9a8561a094255fa59",
          "sha1": "b61a215c124b52c200929695e912ca55a7960d6a",
          "md5": "2a6ab89b88f57203191e5ecb1acfc4f2"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.4.3"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.4.3"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.4.3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-common-1.20.1-0.4.3-sources.jar",
          "url": "vtil-common-1.20.1-0.4.3-sources.jar",
          "size": 93895,
          "sha512": "9c3c737e753c71738839796a198334d9e00f2c1d808c00dfc4c577327467b3190db93e241dc8a6c19599259cc18e887e7410e2d07252da5de8ff68501464ec47",
          "sha256": "0286cc60c51b206eb4b173a8627a3219ba9e9bd58c451d767946cfc30a798f05",
          "sha1": "688d0cf553f8d21ec7bd93fe313805b8f72986ce",
          "md5": "cfc1a677d9ad30a84d4d7a2c58b6f640"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.4.3"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.4.3"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.4.3"
        }
      ]
    }
  ]
}
