{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-fabric-1.20.1",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.5.1.jar",
          "url": "vtil-fabric-1.20.1-0.5.1.jar",
          "size": 587449,
          "sha512": "48c08b2132d7b393c25d3c515e76c5e700f5812c0599541dd3a9aaec65837138d72667f100c81621cd84a32fbe707256c8b8c71ed16512f536df5392a41def98",
          "sha256": "2ce0195acadc749ed4251f03a75659f6692284aa4df4a191b25e19fc457f60f6",
          "sha1": "35e8039026b500495bf57228cdba311fd4f035a8",
          "md5": "b84b25741aa8b5cb53f8ee18b969f83c"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.5.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.5.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+8a3bf60955"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+8a3bf60955"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+8a3bf60955"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+8a3bf60955"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-common-1.20.1",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config",
          "version": {
            "requires": "6.4.90"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+fabric"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric",
          "version": {
            "requires": "6.0.8.0+build.1734-mc1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.5.1.jar",
          "url": "vtil-fabric-1.20.1-0.5.1.jar",
          "size": 587449,
          "sha512": "48c08b2132d7b393c25d3c515e76c5e700f5812c0599541dd3a9aaec65837138d72667f100c81621cd84a32fbe707256c8b8c71ed16512f536df5392a41def98",
          "sha256": "2ce0195acadc749ed4251f03a75659f6692284aa4df4a191b25e19fc457f60f6",
          "sha1": "35e8039026b500495bf57228cdba311fd4f035a8",
          "md5": "b84b25741aa8b5cb53f8ee18b969f83c"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.5.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.5.1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.5.1-sources.jar",
          "url": "vtil-fabric-1.20.1-0.5.1-sources.jar",
          "size": 106322,
          "sha512": "d3e89de3da14c447921f456ca2b9afd71b22d3a573f7bacb479fd98cd6ef101eb02a051766d17d01060bed27525044b66fa73fbee1169f4f39e9b764c11a3c5c",
          "sha256": "3cb38990a25c9a1b3fd9833fbc74cac9ff0243233f2ad5d9f4a615de5f35b806",
          "sha1": "2fc30bb2158641dfb3057993b9a196c704e304bc",
          "md5": "69673e0dea6e42ce5c128f4a449a18e1"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.5.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.5.1"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.5.1"
        }
      ]
    }
  ]
}
