{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-fabric-1.20.1",
    "version": "0.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.4.3.jar",
          "url": "vtil-fabric-1.20.1-0.4.3.jar",
          "size": 584797,
          "sha512": "e3a7945e220ccfc479bdb472093cb5bdca9c98c7cf1c2115e74adab44b33debaf1174ac6a1d653f9071c338c4ce3aac3e7804530579a3393458333715178e393",
          "sha256": "2232971c49e6b4bade5fd9a473bdd65603ac14551050695e8bf2f2f1070a1ac3",
          "sha1": "2d5ac27ce5385cbece5e1a797f6fa70ad3c30955",
          "md5": "78f0e8be7bca937f15106b52414314a3"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.4.3"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.4.3"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.4.3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-common-1.20.1",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config",
          "version": {
            "requires": "6.4.90"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+fabric"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric",
          "version": {
            "requires": "6.0.8.0+build.1734-mc1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.4.3.jar",
          "url": "vtil-fabric-1.20.1-0.4.3.jar",
          "size": 584797,
          "sha512": "e3a7945e220ccfc479bdb472093cb5bdca9c98c7cf1c2115e74adab44b33debaf1174ac6a1d653f9071c338c4ce3aac3e7804530579a3393458333715178e393",
          "sha256": "2232971c49e6b4bade5fd9a473bdd65603ac14551050695e8bf2f2f1070a1ac3",
          "sha1": "2d5ac27ce5385cbece5e1a797f6fa70ad3c30955",
          "md5": "78f0e8be7bca937f15106b52414314a3"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.4.3"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.4.3"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.4.3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.4.3-sources.jar",
          "url": "vtil-fabric-1.20.1-0.4.3-sources.jar",
          "size": 103240,
          "sha512": "043b99249603a14f62a7927337cb9bc0afce47550092a44df8e6e005c4c7873bdd82e1d51c68866abb12b8884704c5a54d156551d2d8b2735d32211655137c7e",
          "sha256": "36273024a1be3c6ff65ae746470eaee360a3057dc3aaa0707c77fad22ca6c3b8",
          "sha1": "5e231947aa69eb439e174c97f2a3589a5a764401",
          "md5": "8cee33524a31ef3b82e3ceed95395edd"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.4.3"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.4.3"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.4.3"
        }
      ]
    }
  ]
}
