{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-fabric-1.20.1",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.6.0.jar",
          "url": "vtil-fabric-1.20.1-0.6.0.jar",
          "size": 603913,
          "sha512": "0fc0894d03bc55d92d93f6f2ff501c7c6199b116b9b821de50f51f8d51aa78ff12361c01e9caabe9bdc503e1126fd53071880e0a69f04c2a54fba4ee7c58d4eb",
          "sha256": "84598a7933213fbb8b27cbc1e96d88b4644abd86bbf4cdcc7124aecf4e1841e8",
          "sha1": "cf0e2235ff3a0b231d6bcf4222283de4ff12139c",
          "md5": "8b1a2e8e8af4f1b22cfeec8909430ced"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.6.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.6.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.6.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+f446f50cff"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-common-1.20.1",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config",
          "version": {
            "requires": "6.4.90"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+fabric"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric",
          "version": {
            "requires": "6.0.8.0+build.1734-mc1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.6.0.jar",
          "url": "vtil-fabric-1.20.1-0.6.0.jar",
          "size": 603913,
          "sha512": "0fc0894d03bc55d92d93f6f2ff501c7c6199b116b9b821de50f51f8d51aa78ff12361c01e9caabe9bdc503e1126fd53071880e0a69f04c2a54fba4ee7c58d4eb",
          "sha256": "84598a7933213fbb8b27cbc1e96d88b4644abd86bbf4cdcc7124aecf4e1841e8",
          "sha1": "cf0e2235ff3a0b231d6bcf4222283de4ff12139c",
          "md5": "8b1a2e8e8af4f1b22cfeec8909430ced"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.6.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.6.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.6.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.6.0-sources.jar",
          "url": "vtil-fabric-1.20.1-0.6.0-sources.jar",
          "size": 111596,
          "sha512": "f4cee05267e953ea36dc844b37b888bb871c3cf87c76e1ac8c82abde547b3b733eb39340c5cb7d784036639e3b9da1fbfd6321b88cf3d4d400c4af31b2e3e2c9",
          "sha256": "291a4be8c0101e8d138843555d7d4f1269ec74f73d37b840e70ca455b51b8f52",
          "sha1": "2fd3967d0ec6372b4706f11e8e67df25f0ff89c2",
          "md5": "fa36d6731760d276c4c553a6f444addb"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.6.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.6.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.6.0"
        }
      ]
    }
  ]
}
