{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-common-1.20.1",
    "version": "0.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.11+c1e5b68ef8"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.6.2.jar",
          "url": "vtil-common-1.20.1-0.6.2.jar",
          "size": 184809,
          "sha512": "ec8fa872937447c9f7ff748ce74404eae70f9ef7f491369cf0c73b1c118510f7208dd86050e5de5338eb80ad5807350afd7f480ea3d836db6037d57e531c979b",
          "sha256": "a90bf63d671f9f19b212de03600ad3c8038a4acb04638d55edcc556473be7270",
          "sha1": "f3425ed1b5a7d7a7ebc3f487e844beba1a619015",
          "md5": "3a3375d9a08739a14f46a6f08c1aba4b"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.6.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.6.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.6.2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-common",
          "version": {
            "requires": "2.4.11+c1e5b68ef8"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-common-1.20.1-0.6.2.jar",
          "url": "vtil-common-1.20.1-0.6.2.jar",
          "size": 184809,
          "sha512": "ec8fa872937447c9f7ff748ce74404eae70f9ef7f491369cf0c73b1c118510f7208dd86050e5de5338eb80ad5807350afd7f480ea3d836db6037d57e531c979b",
          "sha256": "a90bf63d671f9f19b212de03600ad3c8038a4acb04638d55edcc556473be7270",
          "sha1": "f3425ed1b5a7d7a7ebc3f487e844beba1a619015",
          "md5": "3a3375d9a08739a14f46a6f08c1aba4b"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.6.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.6.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.6.2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-common-1.20.1-0.6.2-sources.jar",
          "url": "vtil-common-1.20.1-0.6.2-sources.jar",
          "size": 103827,
          "sha512": "9b77296229f27de3a70d558997ea7dcb0c6e6617f54a2b15296c54d4079a1d3266ed5cc2f34ee6dfbd04300ba555b3244ed91d42d9f2e2bfdc42b91b86e6b284",
          "sha256": "741135b4655dbe19f1e65b1cc56287c381082d8ad7f69c89402f1e9aa40843e8",
          "sha1": "a59d8552ff795bbec5f99d840b14271f85ae1141",
          "md5": "113d0fbfc1f1c2f4563981d837ca418b"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.6.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-common-1.20.1",
          "version": "0.6.2"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "common",
          "version": "0.6.2"
        }
      ]
    }
  ]
}
