{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "vtil-fabric-1.20.1",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.4.0.jar",
          "url": "vtil-fabric-1.20.1-0.4.0.jar",
          "size": 576270,
          "sha512": "abf3559481d94cad824ab3cb9de303e056aff66490d8b5677ad27ac85f5800f00f9bb09c36b52f9ae651e4eb8fc4859362d95a031587cba6d6ce7ba432d2dc11",
          "sha256": "266850f765a84337a719cde385252f2147d46ce7ab75cafdcb692fb6bbfa3cac",
          "sha1": "c3b060cf94eafd9eebcd6b6772415e2c33bd1579",
          "md5": "1c175d99ec982fa7f34827e4412e3fb8"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.4.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.4.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.4.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-common-1.20.1",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config",
          "version": {
            "requires": "6.4.90"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+fabric"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric",
          "version": {
            "requires": "6.0.8.0+build.1734-mc1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.4.0.jar",
          "url": "vtil-fabric-1.20.1-0.4.0.jar",
          "size": 576270,
          "sha512": "abf3559481d94cad824ab3cb9de303e056aff66490d8b5677ad27ac85f5800f00f9bb09c36b52f9ae651e4eb8fc4859362d95a031587cba6d6ce7ba432d2dc11",
          "sha256": "266850f765a84337a719cde385252f2147d46ce7ab75cafdcb692fb6bbfa3cac",
          "sha1": "c3b060cf94eafd9eebcd6b6772415e2c33bd1579",
          "md5": "1c175d99ec982fa7f34827e4412e3fb8"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.4.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.4.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.4.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vtil-fabric-1.20.1-0.4.0-sources.jar",
          "url": "vtil-fabric-1.20.1-0.4.0-sources.jar",
          "size": 98033,
          "sha512": "d4bcfa421934b1d76e577bc5e6c78c77510838aef0e5ac052451ddf5c9ed00538d44b955ec5d595059b99c9b4b17c7fbe7f17d55de62577400fa5d995959d564",
          "sha256": "cb49f04f1cd84edf6da3357e0d6e2877a14d06709da08c7a829db63f3ee8ce24",
          "sha1": "cd25ea6ba569320bf6e499f535f08c5d0a66ae32",
          "md5": "91f62aa5c2dc6dc4415951c0dbdbb680"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.4.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.4.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.4.0"
        }
      ]
    }
  ]
}
