{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vtil",
    "module": "Vtil-fabric-1.20.1",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "Vtil-fabric-1.20.1-0.1.0.jar",
          "url": "Vtil-fabric-1.20.1-0.1.0.jar",
          "size": 532308,
          "sha512": "97f0d1987b9eba9198a38fced578560bce8298f531cf76f76f80e71447a8ac85ca0bbb3dcba0196f589b7e4a23dd7e18f2877126507b0d946146a446658e3740",
          "sha256": "c2ce0b9234e7f25eb9d0e36c7bf7cad8d46e9d59b8ab1b74519e794bf4367248",
          "sha1": "439ed5e398ad810ce7cd2fa4244357723d63ba3f",
          "md5": "47874d2b08b572315a4e33f37f4a4dc8"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "Vtil-fabric-1.20.1",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.1.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "Vtil-common-1.20.1",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config",
          "version": {
            "requires": "6.4.90"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+fabric"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric",
          "version": {
            "requires": "6.0.8.0+build.1734-mc1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "Vtil-fabric-1.20.1-0.1.0.jar",
          "url": "Vtil-fabric-1.20.1-0.1.0.jar",
          "size": 532308,
          "sha512": "97f0d1987b9eba9198a38fced578560bce8298f531cf76f76f80e71447a8ac85ca0bbb3dcba0196f589b7e4a23dd7e18f2877126507b0d946146a446658e3740",
          "sha256": "c2ce0b9234e7f25eb9d0e36c7bf7cad8d46e9d59b8ab1b74519e794bf4367248",
          "sha1": "439ed5e398ad810ce7cd2fa4244357723d63ba3f",
          "md5": "47874d2b08b572315a4e33f37f4a4dc8"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "Vtil-fabric-1.20.1",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.1.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Vtil-fabric-1.20.1-0.1.0-sources.jar",
          "url": "Vtil-fabric-1.20.1-0.1.0-sources.jar",
          "size": 79427,
          "sha512": "393ce5878b2319cf3a611bf343e4b29ec370014ef737359d005c8f63b704fe9778cd663c1ab51a7cde79db3420d95418ff93832a7fae0afc628cd4a5246fa4f2",
          "sha256": "52a80f95d9588a69334b21a174cfbb01168c9f34366f4ee4a1507e2802fd4dc8",
          "sha1": "0fa58a1ce590be0a2c20c29cd6d53f8c146172e2",
          "md5": "47f04210358fcfe2ae18c13ae55a0bac"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vtil",
          "name": "fabric",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "Vtil-fabric-1.20.1",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil",
          "version": "0.1.0"
        },
        {
          "group": "com.github.litermc.vtil",
          "name": "vtil-fabric-1.20.1",
          "version": "0.1.0"
        }
      ]
    }
  ]
}
