{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vsplit",
    "module": "VSplit-fabric-1.20.1",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "VSplit-fabric-1.20.1-0.1.2.jar",
          "url": "VSplit-fabric-1.20.1-0.1.2.jar",
          "size": 570755,
          "sha512": "28b9695af099889fb6b07b7390f2d5111288c33d91e594f6e6064d5a8e3c7cc4c6573c6df28fe76d9bf05cef83407e30ec7cb2ebb893b9bc28ac77120889c044",
          "sha256": "b5499506d19348133a0ea6d6fb295fd6076c7e8a011fb41b1cb2071fde1cf963",
          "sha1": "dea3fd517f7b2fddea033b9bc0bee38654ed9274",
          "md5": "f7a873e5c384f0aa138308c7bb9e144f"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-fabric-1.20.1",
          "version": "0.1.2"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.1.2"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "fabric",
          "version": "0.1.2"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-fabric-1.20.1",
          "version": "0.1.2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.github.litermc.vsplit",
          "module": "VSplit-common-1.20.1",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-forge-1.20.1",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config",
          "version": {
            "requires": "6.4.90"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+fabric"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric",
          "version": {
            "requires": "6.0.8.0+build.1734-mc1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "VSplit-fabric-1.20.1-0.1.2.jar",
          "url": "VSplit-fabric-1.20.1-0.1.2.jar",
          "size": 570755,
          "sha512": "28b9695af099889fb6b07b7390f2d5111288c33d91e594f6e6064d5a8e3c7cc4c6573c6df28fe76d9bf05cef83407e30ec7cb2ebb893b9bc28ac77120889c044",
          "sha256": "b5499506d19348133a0ea6d6fb295fd6076c7e8a011fb41b1cb2071fde1cf963",
          "sha1": "dea3fd517f7b2fddea033b9bc0bee38654ed9274",
          "md5": "f7a873e5c384f0aa138308c7bb9e144f"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-fabric-1.20.1",
          "version": "0.1.2"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.1.2"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "fabric",
          "version": "0.1.2"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-fabric-1.20.1",
          "version": "0.1.2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VSplit-fabric-1.20.1-0.1.2-sources.jar",
          "url": "VSplit-fabric-1.20.1-0.1.2-sources.jar",
          "size": 129151,
          "sha512": "26216efbb9920c559440a6f67347d6bdf1bc4ff15a51f09613492a2fd9f69075631f194e9d4ff95b59800fbb3f8eb9bdb7e82171a2e332b0f7f4a4b8725c06ff",
          "sha256": "8b17ac614350f7a200124b59a5dba27b94d65b87943cca32116482330fe890fa",
          "sha1": "c0229ba7a09ea7774790cf8520fd3237184c68b2",
          "md5": "4bd49ad17092be25c9d93e46248d8b05"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit-fabric-1.20.1",
          "version": "0.1.2"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "vsplit",
          "version": "0.1.2"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "fabric",
          "version": "0.1.2"
        },
        {
          "group": "com.github.litermc.vsplit",
          "name": "VSplit-fabric-1.20.1",
          "version": "0.1.2"
        }
      ]
    }
  ]
}
