{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.litermc.vschunkloader",
    "module": "VSChunkLoader-forge-1.20.1",
    "version": "2.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-forge",
          "version": {
            "requires": "2.4.11+c1e5b68ef8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "VSChunkLoader-forge-1.20.1-2.0.3.jar",
          "url": "VSChunkLoader-forge-1.20.1-2.0.3.jar",
          "size": 1627983,
          "sha512": "00c2a543573e1cc9204e2cadb5ac425b3c890239c7b4d3fca62035e84adc03d312e4f19fa9264f17b018d0b18a64b4755438c9ff017f04aed90ce0850abeba38",
          "sha256": "3dca83b2f019feb4b2cf28830b412c3d6fc26254b1d0b20dda148cbd550257d3",
          "sha1": "630f0580d7ef565706474d938e19d7ca46d3e980",
          "md5": "5c347a2685dae46e525bf3f9faa53017"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "forge",
          "version": "2.0.3"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader",
          "version": "2.0.3"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "VSChunkLoader-forge-1.20.1",
          "version": "2.0.3"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader-forge-1.20.1",
          "version": "2.0.3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "org.joml",
          "module": "joml-primitives",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "impl",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "internal",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.valkyrienskies.core",
          "module": "util",
          "version": {
            "requires": "1.1.0+cf208d8b56"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.valkyrienskies",
          "module": "valkyrienskies-120-forge",
          "version": {
            "requires": "2.4.11+c1e5b68ef8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.litermc.vtil",
          "module": "vtil-forge-1.20.1",
          "version": {
            "requires": "0.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+forge"
          }
        }
      ],
      "files": [
        {
          "name": "VSChunkLoader-forge-1.20.1-2.0.3.jar",
          "url": "VSChunkLoader-forge-1.20.1-2.0.3.jar",
          "size": 1627983,
          "sha512": "00c2a543573e1cc9204e2cadb5ac425b3c890239c7b4d3fca62035e84adc03d312e4f19fa9264f17b018d0b18a64b4755438c9ff017f04aed90ce0850abeba38",
          "sha256": "3dca83b2f019feb4b2cf28830b412c3d6fc26254b1d0b20dda148cbd550257d3",
          "sha1": "630f0580d7ef565706474d938e19d7ca46d3e980",
          "md5": "5c347a2685dae46e525bf3f9faa53017"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "forge",
          "version": "2.0.3"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader",
          "version": "2.0.3"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "VSChunkLoader-forge-1.20.1",
          "version": "2.0.3"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader-forge-1.20.1",
          "version": "2.0.3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VSChunkLoader-forge-1.20.1-2.0.3-sources.jar",
          "url": "VSChunkLoader-forge-1.20.1-2.0.3-sources.jar",
          "size": 135356,
          "sha512": "27a3c0f1c93e06915e246e5427f232cc83d52dd8ab1ad6406018f1bd005aa68fa724860b2f93fb07b2f33262f1ea8d1b1b420b0621b4e939b23d56ee1160af34",
          "sha256": "1247355d8a89735ccd94d38b49435102f88c05ac1ae4f7779b0bb06bfe129fef",
          "sha1": "d1ca8275a49b99a829737154300eee181456aced",
          "md5": "392e90b5d393bc5f86768ad3ae1123d5"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "forge",
          "version": "2.0.3"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader",
          "version": "2.0.3"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "VSChunkLoader-forge-1.20.1",
          "version": "2.0.3"
        },
        {
          "group": "com.github.litermc.vschunkloader",
          "name": "vschunkloader-forge-1.20.1",
          "version": "2.0.3"
        }
      ]
    }
  ]
}
